"""Orchestrates the NVIDIA knowledge base ingestion (brief §8, §5.3):
fetch (kb_collect) -> chunk (kb_chunk) -> embed (NVIDIA NIM) -> render a SQL
seed file for manual review + run in Supabase, mirroring
ingestion/pipeline.py's approach for the Phase 2 startup seed.

Run with: uv run python -m radar_backend.rag.nvidia_kb
"""

from __future__ import annotations

import sys
import uuid
from pathlib import Path

from openai import OpenAI

from radar_backend.core.config import get_settings
from radar_backend.rag.kb_chunk import KbChunk, chunk_sections
from radar_backend.rag.kb_collect import fetch_source
from radar_backend.rag.kb_sources import ALL_SOURCES, KbSource

EMBED_BATCH_SIZE = 32


def embed_passages(texts: list[str]) -> list[list[float]]:
    """input_type="passage" marks these as documents being indexed, as
    opposed to "query" for a user's search text later at retrieval time —
    nemotron-3-embed-1b (like its retired predecessor, nv-embedqa-e5-v5) is an
    asymmetric retrieval model and needs to know which side it's embedding.
    Live-verified against the real API during Phase 3.
    """
    settings = get_settings()
    client = OpenAI(api_key=settings.nvidia_api_key, base_url=settings.nvidia_base_url)
    embeddings: list[list[float]] = []
    for start in range(0, len(texts), EMBED_BATCH_SIZE):
        batch = texts[start : start + EMBED_BATCH_SIZE]
        response = client.embeddings.create(
            input=batch,
            model=settings.nvidia_embedding_model,
            extra_body={"input_type": "passage", "truncate": "END"},
        )
        embeddings.extend(item.embedding for item in response.data)
    return embeddings


def _sql_literal(value: str | int | None) -> str:
    if value is None:
        return "null"
    if isinstance(value, int):
        return str(value)
    return "'" + value.replace("'", "''") + "'"


def _sql_vector_literal(vector: list[float]) -> str:
    return "'[" + ",".join(f"{v:.6f}" for v in vector) + "]'::vector"


def render_sql(rows: list[tuple[KbSource, KbChunk, list[float]]]) -> str:
    lines = [
        "-- Seed: NVIDIA knowledge base chunks (brief §8). Generated by",
        "-- radar_backend.rag.nvidia_kb — see that module for the chunking",
        "-- and embedding approach.",
        "-- Run after backend/db/migrations/0002_nvidia_kb.sql.",
        "",
        "insert into nvidia_kb_chunks",
        "  (id, categoria, tipo, fonte_titulo, url_fonte, secao, chunk_index, conteudo_chunk, embedding)",
        "values",
    ]
    value_rows = [
        "("
        + ", ".join(
            [
                _sql_literal(str(uuid.uuid4())),
                _sql_literal(source.categoria),
                _sql_literal(source.tipo),
                _sql_literal(source.titulo),
                _sql_literal(source.url),
                _sql_literal(chunk.secao),
                _sql_literal(chunk.chunk_index),
                _sql_literal(chunk.texto),
                _sql_vector_literal(vector),
            ]
        )
        + ")"
        for source, chunk, vector in rows
    ]
    lines.append(",\n".join(value_rows) + ";")
    return "\n".join(lines)


def main() -> None:
    settings = get_settings()
    if not settings.nvidia_api_key:
        print("NVIDIA_API_KEY not set — collecting and chunking only, skipping embeddings.", file=sys.stderr)

    pending: list[tuple[KbSource, KbChunk]] = []
    for source in ALL_SOURCES:
        sections = fetch_source(source)
        if not sections:
            print(f"  [skip] {source.titulo}: no content fetched", file=sys.stderr)
            continue
        chunks = chunk_sections(sections)
        print(f"  [ok] {source.titulo}: {len(chunks)} chunk(s)", file=sys.stderr)
        pending.extend((source, chunk) for chunk in chunks)

    print(f"\nTotal chunks: {len(pending)}", file=sys.stderr)

    if not settings.nvidia_api_key or not pending:
        return

    embeddings = embed_passages([chunk.texto for _, chunk in pending])
    rows = [(source, chunk, vector) for (source, chunk), vector in zip(pending, embeddings)]

    output_path = Path(__file__).parents[3] / "db" / "seed" / "nvidia_kb_seed.sql"
    output_path.write_text(render_sql(rows), encoding="utf-8")
    print(f"Wrote {output_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
