-- Seed: hand-curated startups (8), sourced manually from the brief's §7 links
-- before we switched to a scraping pipeline for the remaining ~32 of the 40 target.
-- Run after backend/db/migrations/0001_startups_documentos.sql.
-- Each startup+documentos block uses a fixed uuid literal so the FK can be set
-- without relying on RETURNING (makes it easy to run block by block in the
-- Supabase SQL editor).

-- 1. NeuralMind (AI-native)
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('41fa7703-d38d-47c0-9104-c7aa0eb96048', 'NeuralMind', 'https://neuralmind.ai', 'NLP / IA aplicada (jurídico, regulatório, financeiro, setor público)', 'scale-up (spin-off acadêmico, sem rodada pública divulgada)', 'Campinas, SP', 'Spin-off da Unicamp que desenvolve agentes de IA e busca semântica para bases de conhecimento corporativas; criadora do BERTimbau (BERT em português) e do Jurema 7B, LLM open-source especializado no sistema jurídico brasileiro.', 2017, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte, data_publicacao) values
('41fa7703-d38d-47c0-9104-c7aa0eb96048', 'site_institucional', 'NeuralMind — agentes de IA para busca e recuperação de informação', 'A NeuralMind desenvolve agentes de IA que buscam e recuperam informação em bases de conhecimento corporativas, com respostas fundamentadas em dados concretos (não alucinadas pelo modelo). Produtos incluem o NeuralSearchX, que combina busca semântica, chatbots conversacionais e respostas generativas para consultas complexas. A empresa nasceu de pesquisa da Unicamp e reforça esse rigor acadêmico em suas operações.', 'https://neuralmind.ai', null),
('41fa7703-d38d-47c0-9104-c7aa0eb96048', 'noticia', '6 maiores Startups de Inteligência Artificial no Brasil', 'A NeuralMind é citada como uma das seis maiores startups de IA do Brasil, destacando-se em processamento de linguagem natural (NLP) e visão computacional. Desenvolveu o BERTimbau, modelo de linguagem em português disponível no Hugging Face, com foco em automação de leitura de documentos, extração de informação e detecção de fraude. É referenciada em estudos da FAPESP sobre uso de IA em investigações públicas.', 'https://beanalytic.com.br/blog/startups-de-inteligencia-artificial/', null),
('41fa7703-d38d-47c0-9104-c7aa0eb96048', 'noticia', 'NeuralMind.AI, residente no Parque da Unicamp, lança modelo de IA focado no ambiente jurídico brasileiro', 'A NeuralMind, startup residente no Parque Científico e Tecnológico da Unicamp e apoiada pela FAPESP, lançou o Jurema 7B, um modelo de linguagem (LLM) open-source especializado no sistema jurídico brasileiro, treinado com dados nacionais. A empresa também já havia sido destacada na lista "100 Startups to Watch" de 2021 e atua em automação de operações, compliance e detecção de fraude.', 'https://parque.inova.unicamp.br/neuralmind-ai-residente-no-parque-da-unicamp-lanca-modelo-de-ia-focado-no-ambiente-juridico-brasileiro/', null);

-- 2. Visio.ai (AI-native)
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('c2c971ca-c68a-4d1d-b059-f8bfe8a2b84a', 'Visio.ai', 'https://www.visio.ai', 'Visão computacional para varejo físico / food service (QSR)', 'seed (aporte de R$ 12 milhões, liderado pela DGF Investimentos)', 'São Carlos, SP', 'Sistema operacional de IA para operações de varejo multi-loja: integra dados, sensores de visão computacional e IoT com sistemas de ERP para reduzir o custo da mercadoria vendida (CMV) e aumentar a rentabilidade. Clientes incluem franquias como Subway, Bob''s e BRMania.', 2022, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte, data_publicacao) values
('c2c971ca-c68a-4d1d-b059-f8bfe8a2b84a', 'site_institucional', 'Visio.ai — AI-native operating system for multi-store retail', 'A Visio.ai se descreve como um sistema operacional nativo em IA para operações de varejo com múltiplas lojas, integrando dados, sensores, insights, tarefas e pessoas. Entre as ferramentas oferecidas estão monitor de checkout, detector de fraude, previsão de demanda, controle de fila e controle de porção. A empresa reporta ROI de US$5 para cada US$1 investido e ganho médio de 93% na margem EBITDA das lojas clientes.', 'https://www.visio.ai', null),
('c2c971ca-c68a-4d1d-b059-f8bfe8a2b84a', 'noticia', 'Visio.ai, a startup que usa IA para otimizar franquias, e já está no Bob''s e no Subway', 'Fundada em São Paulo/região em 2022, a Visio.ai usa visão computacional para analisar imagens de câmeras nas lojas cruzadas com dados de sistemas de ERP, ajudando redes de franquias a melhorar eficiência, escala e padronização. A empresa já atende mais de 200 unidades de franquias de alimentação, com redução de 20% no CMV e queda no payback médio das lojas de 36 para 25 meses.', 'https://braziljournal.com/visio-ai-a-startup-que-usa-ia-para-otimizar-franquias-e-ja-esta-no-bobs-e-no-subway/', null),
('c2c971ca-c68a-4d1d-b059-f8bfe8a2b84a', 'release', 'Visio.ai, startup que aumenta a rentabilidade do varejo físico, recebe aporte seed de R$ 12 milhões', 'A Visio.ai recebeu um aporte seed de R$ 12 milhões liderado pela DGF Investimentos, com participação da Alexia Ventures e da Scale-Up Ventures. Os recursos serão usados para expandir a base de clientes no varejo físico, aprofundando o uso de visão computacional e IA para rentabilidade de operações multi-loja.', 'https://startupi.com.br/visio-ai-recebe-aporte-seed-de-r-12-milhoes/', null);

-- 3. Fintalk (AI-native)
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('e73f7aa7-f005-4236-9b59-7c712c8bd659', 'Fintalk', 'https://www.fintalk.ai/pt-BR', 'IA conversacional por voz (atendimento, vendas, cobrança)', 'seed (aporte de R$ 6 milhões, HiPartners), em fase de expansão desde 2024', 'São Paulo, SP', 'Primeira plataforma de IA conversacional por voz do Brasil, capaz de compreender regionalismos e gírias; oferece agentes de IA para atendimento, vendas e cobrança, com mais de 12 milhões de usuários impactados. Ideia concebida em 2019, empresa efetivamente lançada e com primeiros clientes em 2022.', 2019, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte, data_publicacao) values
('e73f7aa7-f005-4236-9b59-7c712c8bd659', 'site_institucional', 'Fintalk — IA Conversacional para Vendas, Atendimento e Cobrança', 'A Fintalk se apresenta como a primeira plataforma de inteligência artificial conversacional do Brasil, com capacidade de compreender regionalismos, gírias e nuances culturais. Oferece agentes de IA para atendimento, vendas e cobrança, além de um "co-piloto" que apoia a performance de times de linha de frente. Suas soluções já impactaram mais de 12 milhões de usuários.', 'https://www.fintalk.ai/pt-BR', null),
('e73f7aa7-f005-4236-9b59-7c712c8bd659', 'blog', 'Our journey — Fintalk', 'Timeline institucional da Fintalk: em 2019 nasceu a pergunta que originou a empresa ("e se empresas pudessem conversar com pessoas como amigos?"); em 2022 a empresa efetivamente abriu as portas e fechou os primeiros clientes; em 2023 passou a ser adotada por grandes instituições financeiras; em 2024 cresceu em time, clientes e impacto, tornando-se referência em automação conversacional; em 2025 expandiu para novas frentes e fronteiras.', 'https://www.fintalk.ai/pt-BR', null),
('e73f7aa7-f005-4236-9b59-7c712c8bd659', 'release', 'Com aporte de R$ 6 milhões, Fintalk quer ser referência em voz no varejo', 'A Fintalk recebeu um aporte de R$ 6 milhões do fundo de venture capital de varejo HiPartners. A startup, fundada por Luiz Lobo (com passagens por Sky, Stone, NET e Unibanco), usa os recursos para consolidar sua posição como referência em IA conversacional por voz aplicada ao varejo.', 'https://startupi.com.br/aporte-de-6-milhoes-fintalk-voz-no-varejo/', null);

-- 4. Blip / Take Blip (AI-native)
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('733a7ebc-1524-4191-b09d-99a24a8d4de4', 'Blip', 'https://blip.ai/blip', 'IA conversacional / customer engagement', 'scale-up (aporte de US$ 70 milhões divulgado)', 'Belo Horizonte, MG', 'Plataforma de inteligência conversacional para atrair, engajar, ouvir e converter clientes via chatbots e IA generativa (integração com Azure OpenAI). Adquiriu a Stilingue (social listening com IA) em 2022 e a GUS, do México, em 2023. Promove o Blip ID, descrito como o maior evento de IA conversacional do mundo.', 1999, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte, data_publicacao) values
('733a7ebc-1524-4191-b09d-99a24a8d4de4', 'site_institucional', 'Blip — Plataforma de Inteligência Conversacional', 'A Blip (razão social Curupira S/A) opera plataforma de inteligência conversacional com quatro pilares: Atraia, Interaja, Escute e Converta. Tem sede em Belo Horizonte (Savassi) e escritório em São Paulo (Itaim Bibi). Entre as soluções complementares estão Stilingue by Blip, Blip Cred e Blip Go, além do evento Blip ID.', 'https://blip.ai/blip', null),
('733a7ebc-1524-4191-b09d-99a24a8d4de4', 'noticia', 'Blip compra STILINGUE: entenda as vantagens', 'A Blip adquiriu a Stilingue em 2022, startup de monitoramento de conversas em canais digitais com IA. A aquisição uniu soluções de social listening com IA a mensageria conversacional voltada à experiência do cliente, reforçando a estratégia de expansão da Blip no mercado de IA conversacional.', 'https://www.blip.ai/blog/institucional/take-blip-compra-stilingue/', null),
('733a7ebc-1524-4191-b09d-99a24a8d4de4', 'noticia', 'Blip recebe novo investimento de US$70 milhões', 'A Blip recebeu um novo aporte de US$ 70 milhões para acelerar sua estratégia de crescimento em inteligência conversacional, incluindo expansão internacional — a empresa também adquiriu a GUS, startup mexicana do setor conversacional, em 2023.', 'https://www.blip.ai/blog/institucional/take-blip-recebe-novo-investimento-70-milhoes/', null);

-- 7. Contabilizei (AI-enabled)
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('bd627373-8cc1-4839-a35b-e8bfc2a97189', 'Contabilizei', 'https://www.contabilizei.com.br/', 'Contabilidade online / fintech B2B', 'scale-up (maior contabilidade online do Brasil)', 'Curitiba, PR', 'Maior escritório de contabilidade online do Brasil, combina contadores certificados (CRC) com tecnologia para abrir empresas e gerir CNPJs de micro e pequenos empreendedores. O core do produto é serviço contábil; uso de automação/tecnologia é acessório, não IA em si.', 2013, '700+ funcionários ("Guardiões")');

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte, data_publicacao) values
('bd627373-8cc1-4839-a35b-e8bfc2a97189', 'site_institucional', 'Contabilizei: a maior contabilidade online do Brasil', 'A Contabilizei se posiciona como a maior contabilidade online do Brasil, com mais de 100 mil clientes em 50+ cidades. Oferece abertura de CNPJ, contabilidade recorrente, emissão de notas fiscais, conta PJ e benefícios como plano de saúde e psicologia para assinantes. Planos partem de R$195/mês.', 'https://www.contabilizei.com.br/', null),
('bd627373-8cc1-4839-a35b-e8bfc2a97189', 'vaga', 'Carreiras | Contabilizei', 'A página de carreiras da Contabilizei lista dezenas de vagas abertas em todo o Brasil, com modelos remoto, híbrido e presencial (escritórios em Curitiba e São Paulo). A empresa chama seus funcionários de "Guardiões" e destaca cultura de diversidade e inclusão.', 'https://www.contabilizei.com.br/trabalhe-na-contabilizei/', null),
('bd627373-8cc1-4839-a35b-e8bfc2a97189', 'noticia', 'Contabilizei (verbete)', 'A Contabilizei foi fundada em Curitiba em 2013 por Vitor Torres e Fábio Bacarin, oferecendo contabilidade online para pequenos empreendedores e autônomos em todo o Brasil.', 'https://pt.wikipedia.org/wiki/Contabilizei', null);

-- 8. Loggi (AI-enabled)
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('7ff1f4aa-307e-49f7-8c95-afd917e92325', 'Loggi', 'https://www.loggi.com/conheca-a-loggi/', 'Logística e last-mile delivery', 'unicórnio (avaliação acima de US$ 1 bi desde 2019)', 'São Paulo, SP', 'Logtech que usa tecnologia (incluindo otimização de rotas) para entregas em todo o Brasil; nasceu de entregas via moto e hoje cobre 100% dos municípios brasileiros, com mais de 500 mil pacotes/dia. Unicórnio desde 2019, com SoftBank e Microsoft entre investidores.', 2013, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte, data_publicacao) values
('7ff1f4aa-307e-49f7-8c95-afd917e92325', 'site_institucional', 'Prazer, somos a Loggi', 'A Loggi usa tecnologia para inovar o envio de encomendas por todo o Brasil, com soluções de entrega nacional (com postagem ou coleta) e entrega local, integração com e-commerces e rastreamento em tempo real. Opera em todas as capitais brasileiras, com mais de 500 mil pacotes entregues por dia via 10 centros de distribuição.', 'https://www.loggi.com/conheca-a-loggi/', null),
('7ff1f4aa-307e-49f7-8c95-afd917e92325', 'noticia', 'Loggi inaugura megagalpão em São Paulo', 'A Loggi inaugurou um megagalpão em São Paulo como parte da expansão de sua malha logística, reforçando a capacidade de atender entregas locais e nacionais para e-commerces de pequeno e grande porte.', 'https://logweb.com.br/loggi-inaugura-megagalpao-em-sao-paulo/', null),
('7ff1f4aa-307e-49f7-8c95-afd917e92325', 'noticia', 'Loggi (verbete)', 'A Loggi foi fundada em julho de 2013 por Fabien Mendez e Arthur Debert, nascendo da observação do potencial logístico das motocicletas nas grandes cidades brasileiras. Atingiu status de unicórnio em 2019, com investidores como SoftBank, Microsoft e GGV Capital, e hoje cobre mais de 4.000 municípios.', 'https://pt.wikipedia.org/wiki/Loggi', null);

-- 9. MadeiraMadeira (non-AI)
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('cf182f24-abc6-4480-9260-2c9c43608665', 'MadeiraMadeira', 'https://www.madeiramadeira.com.br', 'E-commerce de móveis, decoração e materiais de construção', 'Série E / unicórnio (aporte de US$ 190 milhões, jan/2021, liderado por SoftBank e Dynamo)', 'Curitiba, PR', 'Maior varejista online de móveis e produtos para casa do Brasil, com modelo de marketplace/dropshipping e mais de 50 "Guide Shops" físicas. Sem uso relevante de IA divulgado no core do negócio.', 2009, '~2.000 funcionários, 51 lojas físicas');

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte, data_publicacao) values
('cf182f24-abc6-4480-9260-2c9c43608665', 'noticia', 'MadeiraMadeira (verbete)', 'A MadeiraMadeira foi fundada em 1º de agosto de 2009, em São José dos Pinhais (PR), por Daniel Scandian e Marcelo Scandian, após dificuldades de um negócio familiar anterior durante a crise financeira. Opera modelo de dropshipping e marketplace para móveis, materiais de construção, decoração, eletrodomésticos e jardinagem, com sede em Curitiba e cerca de 2.000 funcionários.', 'https://pt.wikipedia.org/wiki/MadeiraMadeira', null),
('cf182f24-abc6-4480-9260-2c9c43608665', 'release', 'Novo unicórnio brasileiro: MadeiraMadeira recebe aporte de US$ 190 milhões', 'Em janeiro de 2021, a MadeiraMadeira captou US$ 190 milhões em rodada Série E colideirada por SoftBank e pelo fundo Dynamo, com participação de VELT Partners, Brasil Capital e Lakewood Capital, tornando-se o 14º unicórnio brasileiro. Os recursos foram direcionados a tecnologia, logística ponta a ponta, expansão de lojas físicas e fusões e aquisições.', 'https://exame.com/pme/novo-unicornio-brasileiro-madeiramadeira-aporte-190-milhoes/', null),
('cf182f24-abc6-4480-9260-2c9c43608665', 'noticia', 'MadeiraMadeira já vale mais de US$ 1 bi, com Dynamo, VELT e Brasil Capital a bordo', 'A reportagem detalha a rodada Série E da MadeiraMadeira, que elevou o valuation da empresa acima de US$ 1 bilhão, com participação de fundos como Dynamo, VELT Partners e Brasil Capital, e histórico de investimento do SoftBank desde 2019.', 'https://braziljournal.com/madeiramadeira-ja-vale-mais-de-us-1-bi-com-dynamo-velt-e-brasil-capital-a-bordo/', null);

-- 10. Printi (non-AI)
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('4f9feb66-0e7a-4dd8-8910-69debfe47147', 'Printi', 'https://www.printi.com.br/', 'Gráfica online / impressão personalizada sob demanda', 'scale-up (aporte minoritário da Vistaprint em 2014; fundadores mantêm controle e empresa independente)', 'Barueri, SP', 'Gráfica 100% online fundada por Mate Pencz e Florian Hagenbuch (também cofundadores do fundo Canary), com catálogo de 200+ produtos personalizáveis (cartões, embalagens, itens promocionais) e parque gráfico próprio em São Paulo. Sem uso de IA no core do negócio — diferencial é software proprietário de otimização de impressão para reduzir desperdício de papel.', 2012, '~440 funcionários (dado de reportagem de 2019)');

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte, data_publicacao) values
('4f9feb66-0e7a-4dd8-8910-69debfe47147', 'site_institucional', 'Printi — A sua gráfica, sempre.', 'A Printi opera como gráfica totalmente online, com parque gráfico em São Paulo e entrega para todo o Brasil, atendendo empresas, autônomos, agências e revendedores. Catálogo cobre papelaria, materiais de marketing, etiquetas, embalagens e itens promocionais, usando tecnologias de impressão digital e offset conforme volume e especificação do pedido.', 'https://www.printi.com.br/', null),
('4f9feb66-0e7a-4dd8-8910-69debfe47147', 'noticia', 'Na era digital, a Printi não para de ganhar dinheiro com o papel', 'A Printi, fundada em 2012 pelos alemães Mate Pencz e Florian Hagenbuch (também cofundadores do fundo Canary), projetava receita anual de R$150 milhões, com cerca de 1.800 pedidos diários e mais de 200 mil clientes. A empresa usa software proprietário para otimizar o encaixe de pedidos em folhas de impressão, reduzindo desperdício, e tinha cerca de 440 funcionários à época da reportagem.', 'https://neofeed.com.br/startups/na-era-digital-a-printi-nao-para-de-ganhar-dinheiro-com-o-papel/', null),
('4f9feb66-0e7a-4dd8-8910-69debfe47147', 'noticia', 'Vistaprint Buys $25 Million Minority Stake In São Paulo-Based Printi', 'Em 2014, a Vistaprint adquiriu uma participação minoritária de US$ 25 milhões na Printi, gráfica online sediada em São Paulo. Os fundadores mantiveram o controle majoritário da empresa, que seguiu operando de forma independente após o investimento.', 'https://techcrunch.com/2014/10/06/vistaprint-buys-25-million-minority-stake-in-sao-paulo-based-printi', '2014-10-06');
