-- Seed: 19 additional startups added post-Phase-8, curated from a list the
-- user supplied (three-tier AI-native / AI-enhanced / no-AI taxonomy), to
-- strengthen the demo video's fit/no-fit narrative with recognizable names.
-- Sourced via radar_backend.ingestion.collect (real fetched page content)
-- plus Wikipedia infoboxes and verified press articles for structured
-- fields (setor/estagio/localizacao/ano_fundacao) and extra documentos —
-- no fabricated data. 3 candidates from the original list were dropped:
-- Kavak (founded in Mexico, fails the founding-location nationality rule),
-- Enter and Woops (identity could not be verified from public sources).
-- A follow-up review pass (nationality + "is this really a startup" check)
-- caught 2 factual errors, fixed here: Nagro's localizacao was guessed as
-- Sao Paulo (real HQ: Uberlandia, MG) and Petlove's ano_fundacao was the
-- 2012 rebrand year, not the real 1999 founding year. Tractian's and Omie's
-- localizacao (both Sao Paulo) rest on the user's own reads of tractian.com
-- and Omie's Glassdoor overview page respectively, rather than a page this
-- pipeline could independently re-fetch and confirm word-for-word (Tractian's
-- cited page doesn't literally combine city+founders+date in one sentence;
-- Glassdoor blocks bot fetches outright) — kept at the user's explicit call
-- after both discrepancies were raised.
-- Run after backend/db/seed/scraped_batch.sql.

-- Nubank
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('02cdd8d0-32c4-48f4-a635-3692a94aa477', 'Nubank', 'https://nubank.com.br', 'Serviços financeiros digitais (conta digital, cartão de crédito, investimentos) com machine learning para risco e fraude', 'capital aberto (IPO na NYSE em dezembro de 2021, ticker NU)', 'São Paulo, SP', 'Maior banco digital independente do mundo, com mais de 100 milhões de clientes na América Latina. Embora seja uma instituição financeira pura (não uma empresa de IA), usa algoritmos de machine learning pesados para precificação de risco, definição de limites de crédito e prevenção de fraudes.', 2013, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('02cdd8d0-32c4-48f4-a635-3692a94aa477', 'site_institucional', 'Somos incansáveis pra você não precisar ser | Nubank', 'Para você Para seu negócio Segurança Saiba Mais Login Empresas Quero ser Nubank Somos incansáveis para você não precisar ser Peça seu Cartão de Crédito e sua Conta do Nubank Digite seu CPF Continuar Para cada momento, um Nubank diferente Nubank Nubank Croma Nubank Ultravioleta Nu Empresas Nubank Controle total da sua vida financeira Conheça Nubank Nubank Croma A experiência que valoriza sua evolução financeira Conheça Nubank Croma Nubank Ultravioleta O melhor cartão para quem ama viajar Conheça Nubank Ultravioleta Nu Empresas Tudo para gerir seu negócio com facilidade Conheça Nu Empresas O melhor cartão de crédito para o seu perfil Cartão Nubank Sem anuidade, sem tarifas abusivas e o mais completo em crédito. Conheça o Cartão Nubank Caixinhas Conta Empréstimos E muito mais Guarde dinheiro de maneira organizada de acordo com seus objetivos. Conheça Pague, receba e transfira na hora, de qualquer lugar. Conheça Consiga ajuda financeira para resolver uma emergência ou realizar um sonho. Conheça Diferentes soluções para o seu dia-a-dia. Conheça Nubank Fique por dentro das novidades Ir para o Blog do Nu Nubank Brand Refresh: como renovamos a identidade visual do Nubank Leia aqui Nubank Proteção em várias camadas: como o Nubank cuida do seu dinheiro e dos seus dados Leia aqui Nubank A era Nu do Inter Miami CF começa agora! Leia aqui Nubank Nu Cine Copan: preservar a história é projetar o futuro Leia aqui Nubank Acelerando para uma nova era: Mercedes-AMG PETRONAS F1 Team e Nu Leia aqui Nubank 5 soluções do Nubank para dar um empurrãozinho na reforma da sua casa Leia aqui Nubank Brand Refresh: como renovamos a identidade visual do Nubank Leia aqui Nubank Proteção em várias camadas: como o Nubank cuida do seu dinheiro e dos seus dados Leia aqui Nubank A era Nu do Inter Miami CF c', 'https://nubank.com.br'),
('02cdd8d0-32c4-48f4-a635-3692a94aa477', 'vaga', 'Carreiras Nu: Faça Parte do Time', 'Carreiras Nu: Faça Parte do Time Carreiras Imprensa Relações com investidores PT Search Carreiras Trabalhe no Nu É sobre fazer o melhor trabalho da sua vida ao lado de pessoas incríveis, construindo um futuro nunca antes imaginado.
Porque, aqui, impossível não está no nosso vocabulário. Junte-se à nossa equipe Faça o extraordinário acontecer É sobre quebrar barreiras, assumir responsabilidades e colocar os clientes no centro. É assim que reinventamos uma das maiores indústrias do mundo. A plataforma de serviços financeiros mais querida do mundo. Empresas Mais Influentes TIME 2021, 2022, 2024, 2026 Melhores Bancos do Mundo FORBES  2019 - 2026 Brazil 2022 - 2026 Mexico Empresas Mais Inovadoras do Mundo Fast Company 2018, 2019, 2023, 2024, 2025 Marcas Bancárias Mais Fortes do Mundo Brand Finance 2026 Mais de 10.000 Nubankers Mais de 50 nacionalidades O futuro é roxinho Junte-se à nossa equipe Um time global Colômbia Bogotá México Cidade do México Estados Unidos Palo Alto, Miami, Washington DC, and Durham Alemanha Berlim Canadá Uruguai Brasil São Paulo Participe dos nossos próximos eventos Vamos permanecer conectados e construir o futuro juntos Mostrar eventos em: Todos fev 20 Q4''25 Earnings Results Conference Call Consumer mar 18 Q6''25 Earnings Results Conference Call Consumer fev 26 Q5''25 Earnings Results Conference Call. Consumer abr 21 Q7''25 Earnings Results Conference Call Consumer O futuro é roxinho O futuro é roxinho O futuro é roxinho O futuro é roxinho O futuro é roxinho O futuro é roxinho O futuro é roxinho O futuro é roxinho O futuro é roxinho O futuro é roxinho O futuro é roxinho O futuro é roxinho A vida no Nu A vida no Nu A vida no Nu A vida no Nu A vida no Nu A vida no Nu A vida no Nu A vida no Nu A vida no Nu A vida no Nu A vida no Nu A vida no Nu A vida no ', 'https://nu.com/pt/carreiras'),
('02cdd8d0-32c4-48f4-a635-3692a94aa477', 'noticia', 'Nubank (verbete)', 'Nubank Ltda. é uma instituição financeira digital brasileira, fundada em 2013 por David Vélez, Cristina Junqueira e Edward Wible, sediada em São Paulo. É o maior banco digital independente do mundo em número de clientes, oferecendo conta digital, cartão de crédito sem anuidade, empréstimos e investimentos via aplicativo. Abriu capital na Bolsa de Nova York (NYSE) em dezembro de 2021.', 'https://pt.wikipedia.org/wiki/Nubank');

-- iFood
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('dacf5f62-9fa1-4fb5-a2d7-37a1714175da', 'iFood', 'https://www.ifood.com.br', 'Delivery e logística de conveniência (comida, mercado, farmácia, pet) com IA para precificação dinâmica e roteirização', 'scale-up (controlada pela Movile e pela Prosus/Naspers)', 'Osasco, SP', 'Gigante de delivery com cerca de 83% de market share no Brasil. Seu core business é logística de conveniência, mas sua IA determina preços dinâmicos, rotas mais rápidas de entrega e sugestões de cardápio hiperpersonalizadas para os mais de 60 milhões de clientes ativos.', 2011, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('dacf5f62-9fa1-4fb5-a2d7-37a1714175da', 'site_institucional', 'iFood | O ecossistema muito além do delivery', 'iFood | O ecossistema muito além do delivery Pede iFood Já! iFood: o maior app de delivery do Brasil O iFood é uma empresa brasileira de tecnologia que aproxima clientes, restaurantes e entregadores de forma simples e prática. E, para proporcionar uma experiência incrível para todo mundo, nossa entrega vai muito além do delivery. Saiba mais sobre o iFood O maior ecossistema de delivery do Brasil O iFood é mais que um app de comida. É uma plataforma completa que conecta clientes, restaurantes, mercados, farmácias, pet shops e entregadores em todo o país. Para clientes Peça comida, mercado, farmácia, pet shop e outras lojas. Tudo em um só app, com entrega rápida e rastreamento. Pede iFood Já Para restaurantes e comércios Mais de 500 mil parceiros já vendem pelo iFood. Aumente seu faturamento com a maior base de clientes do Brasil. Cadastre seu negócio Para entregadores Ganhe dinheiro com flexibilidade e autonomia. Escolha seus horários, acompanhe seus ganhos e conte com suporte dedicado. Seja um entregador Para empresas iFood Benefícios e iFood Ads: soluções corporativas que conectam sua marca a milhões de consumidores todos os dias. Saiba mais Tem iFood para tudo Quando você pede, um negócio cresce e um entregador ganha. Esse é o ecossistema iFood: uma plataforma que movimenta comida, saúde, conveniência e oportunidades para milhões de brasileiros. Uma Sexta à noite sem cozinhar Seu prato favorito entregue na sua porta. Pizza, hambúrguer, japonês, marmita fit e milhares de opções! Pede iFood já Remédio que não pode esperar Remédios, vitaminas, fraldas, dermocosméticos. Entregues rapidinho quando você não pode mesmo esperar! Peça medicamentos Praticidade para os pais de pet Ração, petiscos, areia, brinquedos: tudo entregue por delivery. Praticidade total para você e o seu', 'https://institucional.ifood.com.br'),
('dacf5f62-9fa1-4fb5-a2d7-37a1714175da', 'vaga', 'Arquivo de Carreiras - iFood', 'Arquivo de Carreiras - iFood Pede iFood Já! Pesquisar Pesquisar Carreiras Elas São Tech: iFood abre 50 vagas para mulheres na tecnologia Empresa abre vagas remotas para mulheres que já trabalham com tecnologia e querem avançar na carreira em engenharia de software e ciência de dados 15 de abril de 2026 iFood é uma das melhores empresas para trabalhar no Brasil em 2025 Empresa se destaca na categoria de tecnologia segundo levantamento da Glassdoor Brasil sobre os melhores ambientes de trabalho em 2025 23 de outubro de 2025 Carreira Thiago Cardoso conta como o iFood vem liderando a revolução em IA e Big Data Saiba como o iFood usa IA e Big Data para inovar e melhorar a experiência do usuário pela visão do nosso diretor Thiago Cardoso. Confira! 13 de dezembro de 2024', 'https://institucional.ifood.com.br/carreiras/'),
('dacf5f62-9fa1-4fb5-a2d7-37a1714175da', 'noticia', 'iFood (verbete)', 'iFood é uma empresa brasileira de tecnologia fundada em 2011, com sede em Osasco (SP), que opera a maior plataforma de delivery do Brasil. Conecta clientes, restaurantes, mercados, farmácias e entregadores em mais de 1.500 cidades, processando mais de 180 milhões de pedidos mensais. É controlada pela Movile e pela holandesa Prosus (Naspers).', 'https://pt.wikipedia.org/wiki/IFood');

-- Tractian
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('416219b9-5668-4bc8-b4f9-ef3274d9fdc1', 'Tractian', 'https://tractian.com', 'IoT industrial + IA para manutenção preditiva', 'scale-up (Series C de R$ 700 milhões / US$ 120 milhões, valuation de R$ 4 bilhões)', 'São Paulo, SP', 'Conecta sensores físicos de IoT em maquinários industriais a algoritmos de aprendizado de máquina para prever quebras em fábricas antes que aconteçam. Mais de 100 mil sensores próprios já instalados, monitorando vibração, temperatura e padrões de funcionamento em tempo real.', 2019, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('416219b9-5668-4bc8-b4f9-ef3274d9fdc1', 'site_institucional', 'Tractian | Manutenção Preditiva & Saúde do Ativo Unificada', 'Tractian | Manutenção Preditiva & Saúde do Ativo Unificada MONITORAMENTO DA SAÚDE DE ATIVOS Proteja sua operação.
Reduza paradas não planejadas. Identifique falhas antes que afetem a produção com sensores e IA projetados para o chão de fábrica. Agende uma demo Veja nossos planos Escolha por onde começar Monitoramento Tempo Real Prevenção de Downtime Saúde do Ativo Inteligência de Processo Diagnóstico de Falhas Lubrificação Preditiva Visibilidade Total da Planta Relatórios e Indicadores Integrações com CMMS Agende uma demo Escolha por onde começar Monitoramento Tempo Real Prevenção de Downtime Saúde do Ativo Inteligência de Processo Diagnóstico de Falhas Lubrificação Preditiva Visibilidade Total da Planta Relatórios e Indicadores Integrações com CMMS Monitoramento Tempo Real Prevenção de Downtime Saúde do Ativo Inteligência de Processo Diagnóstico de Falhas Lubrificação Preditiva Visibilidade Total da Planta Relatórios e Indicadores Integrações com CMMS Presente em 1.500 indústrias em todo o mundo Líder em IoT e Gestão de Ativos no G2 Entre as melhores empresas de IA do mundo', 'https://tractian.com'),
('416219b9-5668-4bc8-b4f9-ef3274d9fdc1', 'blog', 'Tudo sobre Manutenção Industrial - Blog', 'Tudo sobre Manutenção Industrial - Blog Tractian lança sensor de vibração e ultrassom para monitoramento preditivo Conheça o novo sensor ultrassônico da Tractian, que detecta falhas industriais ao combinar vibração, ultrassom, temperatura e RPM, e antecipa decisões. Continue lendo Últimos Artigos Bebidas Como funciona a manutenção preditiva com IA para plantas de bebidas Por Breno Smanio Guimarães Inteligência Artificial Sincronização entre sensores: como a IA multimodal garante isso Por Jp Voltani ROI ROI na manutenção industrial: em quantos meses a preditiva se paga? Por Alex Vedan Como funciona a manutenção preditiva com IA para plantas de bebidas Cinco passos para montar um programa preditivo que funciona no ambiente de bebidas: do ranking por consequência à resposta única ranqueada no CMMS. Breno Smanio Guimarães Atualizado em 08 set. de 2026 Continuar lendo Sincronização entre sensores: como a IA multimodal garante isso Veja como a IA multimodal garante a sincronização entre sensores industriais e deixa o seu chão de fábrica sob controle e mais funcional. Jp Voltani Atualizado em 04 set. de 2026 Continuar lendo ROI na manutenção industrial: em quantos meses a preditiva se paga? Veja como o monitoramento contínuo, aliado com IA industrial, pode melhor o seu ROI na manutenção industrial e quanto demora para cada ativo. Alex Vedan Atualizado em 04 set. de 2026 Continuar lendo Custo de manutenção como % da receita: como calcular e otimizar Como calcular custo de manutenção como % da receita e usar esse KPI no comitê? Veja o método completo e o benchmark aplicável à sua operação. Erik Cordeiro Atualizado em 04 set. de 2026 Continuar lendo Calculadora ROI: Como o monitoramento de condição aumenta os ganhos Veja como o monitoramento de condição pode aumentar o ROI da sua', 'https://tractian.com/blog'),
('416219b9-5668-4bc8-b4f9-ef3274d9fdc1', 'noticia', 'Tractian inaugura AI Center em São Paulo', 'Fundada em 2019 por Igor Marinelli, Gabriel Lameirinhas e Leonardo Vieira, a Tractian desenvolve soluções integradas de sensores industriais, software e inteligência artificial para aumentar a confiabilidade e a eficiência operacional de ativos industriais. Após levantar R$ 700 milhões em sua rodada Série C no final de 2024, a empresa anunciou a construção do Tractian AI Center, um espaço de 10.000 m² na Zona Sul de São Paulo, com R$ 60 milhões em investimento (incluindo financiamento da FINEP).', 'https://tractian.com/blog/tractian-inaugura-ai-center-em-sao-paulo'),
('416219b9-5668-4bc8-b4f9-ef3274d9fdc1', 'noticia', 'Tractian capta R$ 700 milhões e expande manutenção preditiva', 'A Tractian fechou uma rodada Série C de R$ 700 milhões (US$ 120 milhões), atingindo valuation de R$ 4 bilhões — um dos maiores aportes recentes entre startups brasileiras de IA industrial. A empresa nasceu em 2019 e opera um centro de IA de 10.000 m² em São Paulo, combinando sensores próprios com software de análise para antecipar falhas em máquinas industriais.', 'https://tecnovix.com.br/tractian-capta-r-700-milhoes-e-expande-manutencao-assistida-para-fabricas-globais');

-- Asaas
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('8e00b64f-3cce-4c46-b84c-0306a8d84529', 'Asaas', 'https://asaas.com', 'Conta digital PJ / meios de pagamento para PMEs, com IA para análise de comportamento de pagamento', 'scale-up', 'Joinville, SC', 'Conta digital especializada em PMEs. Automatiza cobranças (boleto, PIX, cartão) e utiliza modelos de análise de comportamento de pagamentos para mitigar inadimplência e antecipar recebíveis dos seus clientes.', 2010, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('8e00b64f-3cce-4c46-b84c-0306a8d84529', 'site_institucional', 'Conta digital PJ completa e sem mensalidade', 'Conta digital PJ completa e sem mensalidade Conta digital PJ completa e sem mensalidade Ofereça diferentes formas de pagamento, gerencie cobranças, emita notas, antecipe recebíveis e pague fornecedores. Tudo em um só lugar. Cadastre-se agora! Criar conta grátis Ao clicar você aceita receber nossas comunicações, conforme Política de Privacidade Aqui sua empresa tem tudo que precisa em um só lugar Sem o Asaas Com o Asaas Criar conta grátis Faça tudo com a sua conta digital PJ, tudo mesmo Venda parcelado sem medo de levar calote Consulte informações cadastrais, pendências financeiras e o score de crédito de seu cliente antes de fechar a venda. Negative os devedores no Serasa Recupere o dinheiro das cobranças vencidas com a negativação no Serasa. É uma opção muito mais prática e barata que o protesto de boletos. Reduza cerca de 80% da inadimplência Envie notificações automáticas antes e depois do vencimento. Você escolhe os canais: WhatsApp, e-mail, SMS ou robô de voz. Ofereça várias formas de pagamento Personalize as condições de cobrança e venda mais com Pix , cartão de crédito e débito , link de pagamento , e boleto bancário Gerencie seu dinheiro como e quando quiser Desfrute os benefícios de uma conta digital completa para sua empresa, com movimentações gratuitas todo mês e cartão de crédito sem anuidade. Tenha um fluxo de caixa saudável Ganhe mais liquidez nas vendas a prazo ao antecipar recebíveis de boleto e cartão de crédito. É mais barato do que fazer um empréstimo. Pare de perder tempo com burocracia Com a automação de notas fiscais , você cadastra os dados da sua empresa apenas uma vez e se livra da papelada para sempre. Centralize as operações da sua empresa Gerencie os recebíveis, acompanhe as vendas e controle o estoque em um único lugar. Nosso ERP não tem lim', 'https://www.asaas.com'),
('8e00b64f-3cce-4c46-b84c-0306a8d84529', 'vaga', 'Asaas - Login', 'Asaas - Login Acesse sua conta Esqueci minha senha Primeira vez por aqui? Crie sua conta', 'https://www.asaas.com/login/auth'),
('8e00b64f-3cce-4c46-b84c-0306a8d84529', 'noticia', 'Asaas (verbete)', 'Asaas é uma empresa brasileira de software fundada em 2010, sediada em Joinville (SC), especializada em contas digitais PJ, emissão de cobranças e antecipação de recebíveis para pequenas e médias empresas.', 'https://pt.wikipedia.org/wiki/Asaas');

-- Wellhub
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('696ef67e-2e91-4b9a-a8c0-6599aaa94383', 'Wellhub', 'https://wellhub.com', 'Benefício corporativo de bem-estar (fitness, saúde mental, nutrição) com recomendações baseadas em dados de uso', 'scale-up (unicórnio desde junho de 2019; rebranding para Wellhub em abril de 2024)', 'São Paulo, SP', 'Plataforma global de benefício corporativo de bem-estar, presente em mais de 100 mil academias e estúdios (42 mil no Brasil). Utiliza o histórico de dados de milhões de usuários para recomendar treinos, terapia, nutrição e sono, e para reter clientes corporativos.', 2012, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('696ef67e-2e91-4b9a-a8c0-6599aaa94383', 'site_institucional', 'Wellhub | Opções diárias de bem-estar para todos os colaboradores', 'Wellhub | Opções diárias de bem-estar para todos os colaboradores Login BR Argentina Belgique Brasil Canada Chile Deutschland España France Ireland Italia Luxembourg México Nederland Portugal România United Kingdom United States Wellhub Logo Começar Empresas Solicitar cotação gratuita Colaboradores Encontre seu plano Parceiros Seja nosso parceiro Wellhub Logo Começar Login Procurar academias e apps Planos e preços Para colaboradores Para empresas Para empresas Para colaboradores Para parceiros Seja nosso parceiro Integração ao Wellhub Personal trainers Contato parceiros logados Recursos Recursos do Wellhub Blog Relatório do Crescimento do Mercado Fitness 2026 Central de Ajuda Novidades Planos de bem-estar que os colaboradores adoram O Wellhub gera engajamento real, conectando os colaboradores a opções para atividade física, mindfulness, nutrição e qualidade do sono em uma única assinatura pensada para todos os tipos de estilo de vida e orçamentos. Para empresas E-mail corporativo E-mail corporativo Você concorda que o Wellhub use suas informações para entrar em contato sobre nossos produtos e serviços. Dúvidas? Consulte nossa Política de Privacidade . Solicitar cotação gratuita Você concorda que o Wellhub use suas informações para entrar em contato sobre nossos produtos e serviços. Dúvidas? Consulte nossa Política de Privacidade . Para colaboradores Sua empresa oferece Wellhub? Sua jornada de bem-estar começa aqui. Encontre seu plano Amado por colaboradores de empresas como: Ir para Solicitar cotação Como funciona o Wellhub Como funciona o Wellhub Empresas e colaboradores investem para oferecer e ter acesso à nossa plataforma de bem-estar corporativo. Empresas e colaboradores investem para oferecer e ter acesso à nossa plataforma de bem-estar corporativo. As empresas of', 'https://wellhub.com'),
('696ef67e-2e91-4b9a-a8c0-6599aaa94383', 'release', 'Adeus, Gympass. Bem-vindo, Wellhub.', 'Em abril de 2024 o Gympass mudou de marca para Wellhub, evoluindo de um ''passe de academia'' para uma plataforma de bem-estar holístico que inclui mindfulness, terapia, nutrição e qualidade do sono para colaboradores. Segundo a empresa, o novo nome e o logo circular (''Wellness Wheel'') simbolizam uma plataforma centralizada de bem-estar integrado, atendendo colaboradores, empresas contratantes e parceiros de academia/bem-estar.', 'https://wellhub.com/pt-br/blog/press-releases/bem-vindo-wellhub-uma-mensagem-de-nosso-cmo/'),
('696ef67e-2e91-4b9a-a8c0-6599aaa94383', 'noticia', 'De Gympass para Wellhub: "troca do nome não é um tiro no pé"', 'O Gympass, unicórnio brasileiro fundado há 12 anos por Cesar Carvalho, Vinicius Ferriani e João Thayro, rebatizou-se Wellhub em 2024 para refletir sua expansão para além do acesso a academias, incluindo saúde mental, nutrição e sono. Segundo o cofundador João Barbosa, o esforço de dois anos buscou eliminar a confusão do nome literal ''gym pass'' durante a expansão internacional. A empresa crescia de 40% a 50% ao ano, com fluxo de caixa sustentável, focada em consolidar mercados nos EUA, Europa e América Latina.', 'https://startups.com.br/negocios/de-gympass-para-wellhub-troca-do-nome-nao-foi-um-tiro-no-pe/');

-- Creditas
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('b1070da8-5f14-4a7a-aa5b-99e7828c4938', 'Creditas', 'https://www.creditas.com', 'Crédito com garantia (imóveis, veículos), consignado e seguros, com motor de decisão digital', 'scale-up (unicórnio desde dezembro de 2020, avaliada em US$ 1,75 bi)', 'São Paulo, SP', 'Opera crédito com garantia (imóveis/veículos), consignado privado, seguros e financiamentos. Combina as esteiras analógicas de cartório e vistoria com motores de decisão altamente digitais para baratear juros frente ao crédito bancário tradicional.', 2012, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('b1070da8-5f14-4a7a-aa5b-99e7828c4938', 'site_institucional', 'Empréstimo com a menor taxa do mercado | Creditas', 'Empréstimo com a menor taxa do mercado | Creditas Levamos até sua empresa benefícios que vão muito além do crédito consignado. Tem programas de educação financeira, antecipação de salário e cartão de benefícios flexíveis. Tudo para cuidar da saúde financeira das pessoas.', 'https://www.creditas.com'),
('b1070da8-5f14-4a7a-aa5b-99e7828c4938', 'noticia', 'Creditas (verbete)', 'Creditas é uma fintech brasileira fundada em 2012, sediada em São Paulo, especializada em empréstimo com garantia de imóvel, empréstimo com garantia de veículo, consignado privado, seguros, financiamentos e benefícios corporativos.', 'https://pt.wikipedia.org/wiki/Creditas'),
('b1070da8-5f14-4a7a-aa5b-99e7828c4938', 'noticia', 'Novo unicórnio brasileiro: Creditas recebe aporte de US$ 255 milhões', 'A Creditas, fintech fundada em 2012 pelo espanhol Sergio Furio (originalmente como BankFacil, um comparador de produtos financeiros, com pivô em 2016 para crédito com garantia), tornou-se unicórnio brasileiro em dezembro de 2020 ao receber uma rodada Série E de US$ 255 milhões liderada pelo LGT Lightstone, avaliada em US$ 1,75 bilhão — mais que o dobro da avaliação anterior de US$ 750 milhões em julho de 2019. O aporte financiou expansão para novos produtos, mercados e operações no México.', 'https://exame.com/pme/novo-unicornio-brasileiro-creditas-recebe-aporte-de-us-255-milhoes/');

-- Neon
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('41dbc784-6883-45dd-991f-995b42ae7d69', 'Neon', 'https://neon.com.br', 'Conta digital / cartão de crédito, com motores analíticos para aprovação de crédito', 'scale-up (Series C de US$ 300 milhões, 2020)', 'São Paulo, SP', 'Focada na democratização financeira, a fintech agilizou o processo de aprovação de crédito e abertura de contas com motores analíticos avançados. Fundada por Pedro Conrade em 2016 como a primeira conta 100% digital do Brasil.', 2016, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('41dbc784-6883-45dd-991f-995b42ae7d69', 'site_institucional', 'Neon: conta digital com cartão de crédito e CDB Neon', 'Neon: conta digital com cartão de crédito e CDB Neon Faça seu cadastro Cartão de crédito Neon sem anuidade Você está a poucos cliques de abrir uma conta digital e solicitar o cartão de crédito Neon . Aproveite Conheça a Neon Uma conta digital completa com mais de 32 milhões de clientes e investidores globais . Conhecer mais Pix na Neon: Aponte a câmera e pague com saldo ou crédito Com a Lente Neon , seu Pix é mais rápido. Aponte a câmera e pague com o saldo da sua conta ou utilize o limite do seu cartão de crédito. Conheça o Pix na Neon Neon: conta digital completa Na conta digital Neon você encontra CDB, cartão de crédito sem anuidade e muito mais! Abra sua conta CDB Neon: comece com R$ 1 Dinheiro seguro, resgate imediato e rendimento maior do que na poupança. Conheça o CDB Neon Empréstimo pessoal Neon Aqui você tem empréstimo pessoal fácil na palma da mão. Simule e solicite o seu ! Simule seu empréstimo Empréstimo Consignado Neon Com o empréstimo consignado da Neon, você garante as menores taxas com a praticidade do desconto direto em folha. Simule agora Tudo sobre a migração MEI Fácil para o app Neon! Continue cuidando do seu negócio com os serviços da MEI Fácil , agora com as vantagens da conta digital Neon . Saiba mais Pra cada fase da jornada, uma solução Neon Cartão de crédito Neon Sem anuidade CDBs Neon Seu dinheiro rende mais do que na poupança Empréstimo pessoal Fazer empréstimo nunca foi tão fácil Viracrédito Neon Mais limite no cartão de crédito Abra sua conta com cartão e descomplique o crédito Na conta digital Neon você tem cartão de crédito sem anuidade e pode ajustar seu limite direto pelo aplicativo. Pedir meu cartão CDB Neon para guardar dinheiro O CDB Neon é seguro e rende mais do que a poupança! Você guarda dinheiro em poucos cliques e tem rentabilid', 'https://neon.com.br'),
('41dbc784-6883-45dd-991f-995b42ae7d69', 'blog', 'Neon: conta digital com cartão de crédito, CDB e Pix', 'Neon: conta digital com cartão de crédito, CDB e Pix Ops. Não encontramos essa página, mas temos um monte de outras aqui para você. ir para a home', 'https://neon.com.br/blog'),
('41dbc784-6883-45dd-991f-995b42ae7d69', 'noticia', 'Neon (fintech) — verbete', 'Neon é uma fintech brasileira fundada em 2016, autorizada pelo Banco Central do Brasil, que atua como conta de pagamento, emissão de moeda eletrônica e de instrumento pós-pago. Oferece cartões de débito e crédito com a bandeira Visa em parceria com o Banco BV.', 'https://pt.wikipedia.org/wiki/Neon_(fintech)');

-- Omie
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('fb513271-31b4-45e2-8535-8d2321e86314', 'Omie', 'https://www.omie.com.br', 'ERP na nuvem e ecossistema financeiro para PMEs, com automação contábil', 'scale-up (candidata a unicórnio segundo a Distrito)', 'São Paulo, SP', 'Sistema de gestão na nuvem e ecossistema financeiro focado em PMEs, que agiliza processos contábeis eliminando a digitação manual de notas fiscais. Fundada em 2013 por Marcelo Lombardo e Rafael Olmos, hoje com mais de 150 mil clientes ativos.', 2013, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('fb513271-31b4-45e2-8535-8d2321e86314', 'site_institucional', 'Sistema de gestão ERP online - Solução para empresas', 'Sistema de gestão ERP online - Solução para empresas Reforma Tributária: risco para quem não se prepara. Oportunidade para quem se antecipa. Saiba mais Quero conhecer Teste grátis Entrar MENU omie sistema de gestão online Sistema de gestão com conta PJ gratuita integrada, tudo em um só lugar. O sistema ERP que descomplica sua gestão. Quero conhecer Reduza custos e ganhe até 20x mais eficiência em suas operações Omie no seu WhatsApp Vendas e NF-e Serviços e NFS-e Finanças Compras, estoque e produção Teste grátis por 7 dias Sistema de Gestão POR R$ 0 ,00 Sistema 100% na nuvem Suporte premium ao cliente Não precisa de cartão de crédito Cancelamento rápido e a qualquer momento Contratação online, simples e super prática Testar grátis Reduza custos e aumente a eficiência da sua empresa Marcas que crescem com a Omie Dúvidas frequentes O que é um sistema de gestão completo para empresas? Um sistema de gestão completo para empresas é uma plataforma que centraliza todas as operações vitais de um negócio em um único ambiente digital. Em vez de depender de planilhas isoladas e softwares que não se comunicam, a empresa passa a contar com uma visão integrada de vendas, finanças, estoque e emissão de notas fiscais. Nesse contexto, o sistema de gestão Omie atua como uma verdadeira espinha dorsal tecnológica. Isso porque garante que os dados fluam de forma automática e sem erros entre os diferentes departamentos. Como resultado, o empreendedor passa a tomar decisões baseadas em números reais e atualizados, além de reduzir significativamente o tempo gasto com tarefas manuais e retrabalho. Como funciona a integração entre sistema de gestão e conta digital? A integração entre sistema de gestão e conta digital acontece por meio do conceito de ERP Banking, no qual os serviços financeiros op', 'https://www.omie.com.br'),
('fb513271-31b4-45e2-8535-8d2321e86314', 'blog', 'Blog para Contadores e Empreendedores - Omie ERP online', 'Blog para Contadores e Empreendedores - Omie ERP online Reforma Tributária: risco para quem não se prepara. Oportunidade para quem se antecipa. Saiba mais Quero conhecer Teste grátis Entrar MENU Blog Omie Artigos para impulsionar seu negócio Conteúdo exclusivo sobre Gestão para Empreendedores e Contadores, toda semana! E-mail Receber conteúdo Receba os melhores artigos direto no seu e-mail. Sem spam, prometemos! 500+ Artigos 50K Leitores/mês 10+ Novos/semana Ver todos os artigos Sou Empreendedor Ver todas Sou empreendedor MEI Gestão Gestão de pessoas Marketing e vendas Tecnologia e Inovação Compras e Estoque E-commerce Financeiro Reforma Tributária Explorar todas as categorias Sou Contador Ver todas Sou contador Carreira Contábil Contabilidade Digital Contabilidade Empresarial Gestão Contábil Serviços Contábeis Legislação e Tributação Marketing Contábil Explorar todas as categorias OMIE Ver todas Omie Novidades Omie Omie Academy Eventos ERP na prática Omie Newsletter Omie Franquias Relatório IODE Imprensa Explorar todas as categorias Sou empreendedor Payback simples: descubra o tempo exato do seu retorno Aprenda a calcular o payback simples de projetos. Avalie o retorno do seu investimento com segurança usando o nosso sistema de gestão. Felipe Beraldi • 29 de setembro de 2026 Posts em destaque Reforma Tributária IBS na reforma tributária: como afeta os impostos? 21 de janeiro de 2025 Reforma Tributária Calculadora reforma tributária: simule e proteja seu negócio 23 de fevereiro de 2026 Reforma Tributária Impacto da reforma tributária no preço dos produtos 16 de fevereiro de 2026 Sou empreendedor Sistema para mercados: saiba como escolher o melhor Omie Digital • 28 de setembro de 2026 Sou empreendedor Lista de infoprodutos mais vendidos: com dicas para vender Omie Digita', 'https://www.omie.com.br/blog/'),
('fb513271-31b4-45e2-8535-8d2321e86314', 'noticia', 'Visão geral - Trabalhar na Omie - Glassdoor', 'Segundo o perfil da empresa no Glassdoor, a Omie foi fundada na Cidade de São Paulo, no estado de São Paulo, no ano de 2013.', 'https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Omie-EI_IE2483805.13,17.htm');

-- Gupy
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('ae40362b-193b-4138-9dfd-5c21b390b85c', 'Gupy', 'https://www.gupy.io', 'Recrutamento e gestão de RH (recrutamento e seleção, admissão, treinamento, engajamento) com IA de matching', 'scale-up (maior aporte da América Latina em HR Tech: R$ 500 milhões, SoftBank e Riverwood, 2022)', 'São Paulo, SP', 'Líder absoluta em recrutamento no país. Utiliza IA para ler currículos e ordenar os candidatos com maior afinidade técnica às vagas anunciadas, além de soluções de admissão, treinamento, engajamento e performance.', 2015, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('ae40362b-193b-4138-9dfd-5c21b390b85c', 'site_institucional', 'Gupy | Impulsione o seu RH', 'Gupy | Impulsione o seu RH Pular para o c onteúdo principal ? Preciso de Ajuda Sou uma empresa cliente Sou uma empresa e quero conhecer a Gupy Sou uma pessoa candidata Agentes de IA de ponta a ponta Soluções inteligentes para resultados extraordinários em Gestão de Pessoas Gestão unificada do colaborador, da contratação à alta performance, com IA e dados integrados orientando cada decisão. A escolha de mais de 4.000 empresas no Brasil A plataforma completa de IA para toda a jornada de pessoas Recrutamento e Seleção Admissão Treinamento Engajamento Performance Central de Talentos Atraia os candidatos certos e selecione com inteligência e velocidade Use Agentes de IA com a segunda maior base de talentos do país. Reduza em até 65% o tempo de fechamento de suas vagas com a Contratação via WhatsApp . Garanta processos mais transparentes e assertivos. Saiba mais sobre o produto Contrate novos colaboradores com agilidade e experiência encantadora Acelere em até 50% o tempo de admissão com validação de documentos em 120 minutos e reduza seu SLA com notificações e acesso sem login via WhatsApp. Centralize processos. Elimine retrabalho e conquiste 85% de satisfação. Saiba mais sobre o produto Capacite times de alta performance com aprendizado que engaja Gere até 3x mais engajamento com treinamentos gamificados acessíveis em qualquer dispositivo. Crie cursos com IA em 5 minutos ou use 350 conteúdos prontos. Saiba mais sobre o produto Identifique riscos e atue preventivamente para reter talentos Reduza em até 24% o turnover com algoritmos preditivos de 85% de assertividade . Monitore o clima em tempo real e tome decisões baseadas em dados, não intuição. Saiba mais sobre o produto Avalie com precisão e desenvolva pessoas com base em dados Simplifique a gestão com avaliações 360° per', 'https://www.gupy.io'),
('ae40362b-193b-4138-9dfd-5c21b390b85c', 'blog', 'Blog de RH | Gupy', 'Blog de RH | Gupy Conteúdo principal Buscar no blog Blog Ir para o Site da Gupy Falar com vendedor Blog de RH | Gupy Certificações Impulsione a sua carreira com metodologias inovadoras! Ler mais Impulsione a sua carreira com metodologias inovadoras! Performance e Desenvolvimento Decodificando o DNA da alta performance Ler mais Decodificando o DNA da alta performance Recrutamento e Seleção Recursos Humanos: entenda o que é o RH, o que ele faz e como ter uma equipe de sucesso! Ler mais Recursos Humanos: entenda o que é o RH, o que ele faz e como ter uma equipe de sucesso! Certificações Impulsione a sua carreira com metodologias inovadoras! Ler mais Impulsione a sua carreira com metodologias inovadoras! Performance e Desenvolvimento Decodificando o DNA da alta performance Ler mais Decodificando o DNA da alta performance Recrutamento e Seleção Recursos Humanos: entenda o que é o RH, o que ele faz e como ter uma equipe de sucesso! Ler mais Recursos Humanos: entenda o que é o RH, o que ele faz e como ter uma equipe de sucesso! Mais lidas Cultura organizacional: o que é, importância, tipos e exemplos Cultura organizacional é um conjunto de elementos (crenças, valores e normas) que influenciam o clima de uma empresa. Saiba mais! escrito por: Gupy Leitura: 15min Ler mais Cultura organizacional: o que é, importância, tipos e exemplos Carta de apresentação: veja modelo pronto, como fazer e mais! escrito por: Mariana Dias | GUPY Leitura: 11min Ler mais Carta de apresentação: veja modelo pronto, como fazer e mais! O que é psicologia organizacional, para que serve e quais as áreas de atuação? escrito por: Bruna Guimarães | GUPY Leitura: 5min Ler mais O que é psicologia organizacional, para que serve e quais as áreas de atuação? Receba os melhores conteúdos de RH, em primeira mão, dir', 'https://www.gupy.io/blog'),
('ae40362b-193b-4138-9dfd-5c21b390b85c', 'release', 'R$500 milhões: recebemos o maior aporte em plataforma de RH da América Latina', 'A Gupy, fundada em 2015, recebeu um aporte de R$ 500 milhões liderado pelo SoftBank e pela Riverwood, com participação da Endeavor Catalyst — o maior investimento em uma plataforma de RH na América Latina e o maior em uma startup brasileira fundada por mulheres. Com mais de 22,5 milhões de usuários e 1.500+ clientes em mais de 10 países latino-americanos, a empresa cresce mais de 100% ao ano desde a fundação e usa o aporte para expansão geográfica e integração de soluções de recrutamento, admissão, treinamento e engajamento.', 'https://www.gupy.io/blog/aporte-500-milhoes-gupy');

-- Cortex
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('dd0f6214-a785-434b-ac01-3561572ff93d', 'Cortex', 'https://www.cortex-intelligence.com', 'Big Data Analytics e Go-to-Market Intelligence para inteligência de vendas corporativa', 'scale-up (Series C de US$ 48 milhões)', 'São Paulo, SP', 'Referência em Big Data Analytics na América Latina, processa bilhões de dados públicos e privados para dar inteligência de vendas corporativas a grandes corporações, combinando big data, georreferenciamento e modelos avançados de IA.', 2003, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('dd0f6214-a785-434b-ac01-3561572ff93d', 'site_institucional', 'Cortex Intelligence: AI & Data for Business Growth', 'Cortex Intelligence: AI & Data for Business Growth Solutions teste teste Cortex Brand Cortex Geofusion Cortex Growth Cortex Reach Use Cases Media Exposure Reputation in the Media Stock Performance Integrated Reputation Proprietary Channels Resources Vehicles and Journalists Industry Benchmark Trends in the Media Crisis Management Financial Statements Use Cases Expansion Strategy Network Management Sales and Go-To-Market Geomarketing Competition Analysis Market Intelligence Resources Data Layers Maps and Customization Import and Export Use Cases Outbound Prospection Inbound Qualification Allbound Strategy Resources Orquestrador Outreach GTM - Latam Segments Technology Financial B2B Services Use Cases Untapped Market Potential Calibrating Targets Sales Routine Approach Industry and Distributor Connection Resources Panels and Maps Agents GTM Intelligence Augmented Intelligence Learn teste teste Events Cortex Academy Library Go-to-Market Intelligence Portal Login Request a demo Made for humans , powered by AI Augmented intelligence to accelerate your growth The most complete Go-to-Market intelligence platform, combining data, artificial intelligence and the market''s leading experts. From Industry to Retail, from B2B to B2C. Ask for a demo Made for humans , powered by AI Augmented intelligence applied to GTM for The most complete Go-to-Market intelligence platform, combining data, artificial intelligence and the market''s leading experts. From Industry to Retail, from B2B to B2C. Request a demo As empresas líderes estão com a Cortex The leading companies are with Cortex Our Go-to-Market Intelligence platform Our flexible platform allows Cortex to solve different data challenges in Latin America and continuously expand our market presence. Data capture and structuring Our tech', 'https://www.cortex-intelligence.com/en/'),
('dd0f6214-a785-434b-ac01-3561572ff93d', 'blog', 'Blog com conteúdos sobre Marketing, Comunicação e Vendas', 'Blog com conteúdos sobre Marketing, Comunicação e Vendas Portal Intelligence Review Capa Dados na mídia Eventos Pesquisas Entrevistas Opinião Market & Innovation Blog Home do Blog Comunicação Inteligência Marketing Vendas Varejo Indústria Geomarketing Materiais Gratuitos Casos de sucesso Especiais Manual de Gestão da Reputação Cursos Introdução à Comunicação baseada em dados Voltar para a Cortex Assine o Blog Fale com a gente Blog Conteúdo sobre IA e Go-to-Market Intelligence para Vendas, Marketing, Expansão e Comunicação Geomarketing: o que é, vantagens e como usar nos negócios Geomarketing Inteligência Aumentada: o futuro da colaboração humano-máquina Inteligência de mercado Guia completo para elaborar um plano de Comunicação eficaz Comunicação Potencial de mercado inexplorado: desvende oportunidades para o seu negócio Indústria Go-to-Market Intelligence: abordagem cíclica para resultados efetivos Vendas Lead qualificado: o que é e como conseguir para o seu negócio Vendas Cresça com a gente! Aprofunde seus conhecimentos profissionais com nossos artigos ricos e gratuitos Assine o blog Cortex Summit 2026: como a IA Agêntica e as organizações aumentadas estão transformando negócios Confira a cobertura completa do Cortex Summit 2026. Descubra como a IA agêntica e as organizações aumentadas estão transformando a estratégia dos negócios. Inteligência de mercado Agente de IA para Vendas: aprenda a usar Agente de IA para vendas: o que é, como difere da automação, quais tipos existem, quais resultados entregam e como implementar com controle e governança. Vendas Comunicação institucional regionalizada: marcas que falam com o Brasil Comunicação institucional que ignora o Brasil regional perde licença social nos territórios. Veja como adaptar mensagem sem abrir mão de propósito ', 'https://www.cortex-intelligence.com/blog'),
('dd0f6214-a785-434b-ac01-3561572ff93d', 'noticia', 'Big Data analytics startup Cortex secures a $48M Series C round', 'A Cortex Intelligence, fundada em 2003 em São Paulo, é uma empresa de Augmented Intelligence especializada em Go-to-Market que combina inteligência artificial e humana. Recebeu o maior aporte em IA e Big Data da América Latina em 2020, com investidores como Riverwood Capital, SoftBank Latin America Fund, Lightrock, Redpoint Ventures e Endeavor, totalizando mais de US$ 102 milhões captados.', 'https://latamlist.com/big-data-analytics-startup-cortex-secures-a-48m-series-c-round/');

-- Solinftec
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('578675ef-e1dd-455a-b54a-d2cbd3f46513', 'Solinftec', 'https://www.solinftec.com', 'AgTech: sensores + robótica + IA para monitoramento agrícola em tempo real', 'scale-up (multinacional, presente em mais de 10 países)', 'Araçatuba, SP', 'Monitora operações agrícolas globais em tempo real, aliando sensores em tratores à robótica no campo (Solix) para maximizar o rendimento das safras e reduzir uso de insumos. Nasceu em Araçatuba (SP) para o setor sucroenergético e hoje é uma multinacional agtech.', 2007, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('578675ef-e1dd-455a-b54a-d2cbd3f46513', 'site_institucional', 'Solinftec AgTech Solutions - Plataforma de Software', 'Solinftec AgTech Solutions - Plataforma de Software Skip to Main Content Casos de Sucesso Imprensa Carreiras Blog Português English Español Escolha uma Página Impactando o agro através da tecnologia. Fale com um especialista Impactando o agro através da tecnologia. Fale com um especialista QUEM SOMOS Os desafios nos impulsionam Como líder global em inteligência digital para o agro, sabemos que o planeta passa por um momento decisivo: A produção agrícola global precisa crescer em 60% para atender à demanda por alimentos estimada para 2050. Precisaremos nos adaptar com extrema agilidade para conseguir produzir mais em um mesmo espaço de terra. Em 30 anos, as mudanças climáticas podem limitar ainda mais a produtividade na agricultura. Na medida em que aumentamos a produção, devemos simultaneamente diminuir o impacto ambiental para assegurar a qualidade de vida das próximas gerações. NOSSA MISSÃO É DAR A CADA FAZENDA UM FUTURO SUSTENTÁVEL Para os próximos anos, nosso foco está em fornecer soluções reais e eficazes para aumentar a eficiência e reduzir o impacto ambiental da agricultura. Saiba mais Um ecossistema que conecta e opera toda a sua produção Dados, máquinas, logística e inteligência artificial atuando de forma integrada para otimizar a operação em tempo real. A SOLINFTEC entende o seu negócio como ele realmente funciona. Ela atua diretamente nos desafios da operação agrícola, conectando dados operacionais, logísticos, agronômicos e climáticos em um único sistema. Isso permite gestão contínua da operação, com decisões aplicadas no dia a dia da lavoura. A SOLINFTEC transforma dados da sua operação em decisões que melhoram resultado. A plataforma cruza histórico, contexto e dados em tempo real para identificar desvios, antecipar problemas e orientar ações práticas na ', 'https://www.solinftec.com'),
('578675ef-e1dd-455a-b54a-d2cbd3f46513', 'blog', 'Insights from the Solinftec Blog - Solinftec', 'Insights from the Solinftec Blog - Solinftec Skip to Main Content Success Cases Blog News Global Careers English Português Español Select Page The Solinftec Blog Content that transforms data into smarter decisions for agriculture. North American Blog Explore innovative thinking from industry experts to find new ways of solving the most critical issues in agriculture. Solinftec Expands U.S. Footprint 243%, Deploys 100+ Autonomous Robots as It Showcases Next-Generation Solix System at Commodity Classic 2026 North America Solix, technology that lives in the field. North America Combat uncontrollable costs and uncertainty with ag software solutions North America 3 Ways Agtech Software Maximizes Time for Custom Applicators North America How real-time data empowers ag retailers North America Sustainable technologies that reduce environmental impacts Brazil Brazilian agribusiness outlook: understand the sector in depth Brazil , North America Technological innovation in agribusiness: new ways to optimize crops North America Digital agriculture is transforming the sector. Learn more about it! North America Transform your agricultural operations with Solinftec Use global agriculture software solutions to optimize operations. Talk with a team member Join thousands of other farmers, retailers, and co-ops in finding new opportunities to improve efficiency and optimize processes — all in the service of feeding the world.', 'https://www.solinftec.com/en-us/blog/'),
('578675ef-e1dd-455a-b54a-d2cbd3f46513', 'noticia', 'Solinftec atinge maioridade e vislumbra 700 robôs no campo até 2026', 'A Solinftec, agtech brasileira de 18 anos, desenvolve o Solix AG Robotics, um robô autônomo movido a energia solar que usa visão computacional e machine learning para identificar pragas, plantas daninhas e doenças em tempo real, permitindo aplicação localizada de defensivos. A empresa já captou R$ 1,3 bilhão em investimentos e CRAs (incluindo R$ 300 milhões da YvY Capital), opera 50 robôs no Brasil e planeja chegar a 700 até 2026, expandindo agressivamente para os EUA com uma fábrica em Indiana (investimento de US$ 5 milhões).', 'https://forbes.com.br/forbesagro/2025/02/solinftec-atinge-maioridade-e-vislumbra-700-robos-no-campo-ate-2026/');

-- Mottu
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('9fdb480c-df1a-4984-bd99-81ce37f61641', 'Mottu', 'https://mottu.com.br', 'Mobilidade urbana / locação de motocicletas para entregadores', 'scale-up', 'São Paulo, SP', 'Fenômeno do setor de mobilidade: aluga frotas físicas de motocicletas para entregadores a partir de R$ 18-19/dia, presente em mais de 170 cidades. O coração da operação é puramente analógico: compra de peças, manutenção pesada em oficinas presenciais e apoio ao piloto.', 2020, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('9fdb480c-df1a-4984-bd99-81ce37f61641', 'site_institucional', 'Mottu - Aluguel de Motos | A maior do Brasil', 'Mottu - Aluguel de Motos | A maior do Brasil Pular para o conteúdo Carregando… Mottu — Aluguel de motos Mottu Aluguel Aluguéis a partir de R$ 19/dia. Saiba mais Mottu Store Peças e acessórios para fortalecer o seu corre Conhecer loja (abre em nova aba) Mottu Sport ESD A nova Mottu chegou, com tudo o que você queria e muito mais. Conhecer a moto Nossos números A Mottu em números Somos a maior empresa de aluguel de motos do Brasil e seguimos crescendo todos os dias. + 0 Cidades atendidas + 0 K Motos produzidas por ano + 0 K Motos alugadas Depoimentos O que dizem nossos parceiros Veja o que os entregadores que usam a Mottu têm a dizer sobre a experiência. play_arrow A Mottu mudou minha vida. Consegui alugar uma moto de forma rápida e simples, e hoje faço minhas entregas com tranquilidade. play_arrow O suporte da Mottu é incrível. Sempre que preciso de ajuda, tenho atendimento rápido e eficiente. play_arrow Com a Mottu consegui começar a trabalhar sem precisar comprar uma moto. O aluguel cabe no meu bolso e a moto é muito boa. play_arrow Recomendo a Mottu para todos os entregadores. É confiável, acessível e tem motos de qualidade. Sobre nós A maior empresa de aluguel de motos do Brasil Desde 2020, a Mottu conecta entregadores a oportunidades com motos acessíveis e suporte completo. Estamos presentes em mais de 170 cidades e seguimos crescendo para transformar a mobilidade urbana no Brasil. Nossa história Carreiras Venha fazer parte do nosso time A Mottu está sempre em busca de talentos para transformar a mobilidade urbana no Brasil. Vagas em tecnologia Desenvolvedores, product managers, designers e mais. Ver vagas Vagas para mecânicos Mecânicos de motos para nossas unidades em todo o Brasil. Ver vagas Todas as vagas Veja todas as oportunidades disponíveis na Mottu. Ver vaga', 'https://mottu.com.br'),
('9fdb480c-df1a-4984-bd99-81ce37f61641', 'vaga', 'Carreiras - Venha fazer parte da Mottu | Mottu', 'Carreiras - Venha fazer parte da Mottu | Mottu Pular para o conteúdo Carregando… Carreiras Junte-se a uma das Startups que mais cresce na América Latina Quero fazer parte Hoje somos A maior locadora de motos do mundo + 0 Cidades pelo Brasil e México + 0 K Motos Alugadas + 0 K Motos produzidas por ano Business Units Manifesto Mottu A Força de Transformar, Valorizamos a Luta e a Superação Acreditamos em um mundo conectado e simplificado, com soluções tecnológicas que melhoram vidas. Valorizamos a superação, a igualdade, e a união para construir juntos e transformar a forma como pensamos e agimos. Nós somos Mottu. Construindo um Futuro Melhor com Inovação e Igualdade Acreditamos em um mundo conectado e simplificado, com soluções tecnológicas que melhoram vidas. Valorizamos a superação, a igualdade, e a união para construir juntos e transformar a forma como pensamos e agimos. Nós somos Mottu. Cultura “ Nós somos raiz. Nós somos mottu! ” Profundidade "If I had asked people what they wanted, they would have said faster horses." - Henry Ford Adaptive Entende seus gaps de conhecimento e demonstra interesse e capacidade de aprender, efetivamente evoluindo sua bagagem (soft/hard skills e expertise) para atacar problemas cada vez mais complexos ao longo do tempo. Profound Tem um excelente nível analítico e o usa para trazer análises coerentes e profundas baseadas em dados que geram insights aplicáveis. Não é superficial em suas opiniões, entende que a solução para nossos desafios requer profundidade e tem a disciplina e consistência de percorrer todos os degraus necessários, entendendo os problemas na causa raiz. Result Aware Conhece e monitora o desempenho diário/semanal/mensal dos principais KPIs. Guiado por performance medida, ajusta suas ações com base nos números e direciona ', 'https://mottu.com.br/carreiras'),
('9fdb480c-df1a-4984-bd99-81ce37f61641', 'noticia', 'Mottu (verbete)', 'Mottu é uma empresa brasileira de mobilidade urbana fundada em 2020, sediada em São Paulo, especializada na locação de motocicletas para entregadores de aplicativo, com presença em mais de 170 cidades brasileiras.', 'https://pt.wikipedia.org/wiki/Mottu');

-- Cobli
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('d3fae752-589b-4b33-99b6-60ab68ea31de', 'Cobli', 'https://www.cobli.co', 'Telemetria e gestão de frotas comerciais (IoT + videotelemetria)', 'scale-up (mais de R$ 350 milhões captados, liderado por SoftBank/IFC/Fifth Wall)', 'São Paulo, SP', 'Atua em telemetria e gestão de frotas comerciais instalando rastreadores e hardware físico diretamente na entrada OBD dos carros, além de câmeras com IA. Time de mais de 400 pessoas, presente em todos os estados do Brasil, atendendo telecom, transporte, energia e construção civil.', 2017, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('d3fae752-589b-4b33-99b6-60ab68ea31de', 'site_institucional', 'Cobli: Plataforma de gestão para uma frota mais eficiente!', 'Cobli: Plataforma de gestão para uma frota mais eficiente! Rastreamento de frotas Cobli: descomplique sua gestão A plataforma que potencializa sua frota com videotelemetria, telemetria e aplicativos móveis! Reduza custos, melhore a produtividade e otimize jornadas de trabalho com uma plataforma que oferece a visibilidade mais detalhada do mercado. Fale com um especialista Já utiliza o painel Cobli? Acesse aqui 25% de redução de acidentes na frota Saiba mais Solução para os principais problemas da sua gestão O rastreamento com videotelemetria e telemetria permite ter mais controle e visibilidade da operação Custos Eliminação de gastos com combustível, manutenção e custos administrativos. Produtividade Identificação de melhorias, aumentando serviços e entregas. Controle Conformidade operacional e regulamentar para uma gestão com mais fluidez. Segurança Melhores condições de segurança e proteção dos funcionários e terceiros. Experiência Melhor experiência, atendendo as expectativas dos seus clientes. Transforme os dados dos seus veículos em conhecimento e potencialize os seus resultados Videotelemetria Telemetria Cobli Cam Multi Cobli Cam Multi Cobli Cam Fadiga Cobli Cam Fadiga Cobli Cam Cabine Cobli Cam Cabine Cobli Cam Multi : múltiplas câmeras para uma visão 360º Conte com até cinco câmeras posicionadas onde sua operação mais precisa e tenha uma visão completa de tudo o que acontece dentro e fora dos seus veículos. Utilize as gravações das câmeras para apurar acidentes, prevenir fraudes e monitorar o manuseio de cargas e comportamento de passageiros . Analise o modo de condução dos motoristas e conte com a identificação automática de eventos de risco, como excesso de velocidade, distração, fadiga, uso de cigarro e direção perigosa. Tenha registros de diversos ângulos do', 'https://www.cobli.co'),
('d3fae752-589b-4b33-99b6-60ab68ea31de', 'blog', 'Blog da Cobli | Tudo sobre gestão de frotas', 'Blog da Cobli | Tudo sobre gestão de frotas Controle sua frota Controle sua frota ?.map Sistema de frotas no campo: os critérios que a Cooxupé e a FS usaram para escolher Gestão de frotas / 8 de setembro de 2026 Um sistema de gestão de frota no campo funciona quando resolve dois problemas que a operação urbana raramente enfrenta: frota dispersa em propriedades rurais extensas, rodando boa parte do trajeto em estrada de terra, e uma mistura de veículo próprio com terceirizado cobrindo várias regiões ao mesmo tempo. É essa combinação, não uma lista genérica […] Leia mais » Como apresentar os resultados da frota para a diretoria? Gestão de frota baseada em dados / 4 de setembro de 2026 Uma apresentação de resultados da frota emperra quando o indicador não vira argumento financeiro. O método de três perguntas que a diretoria faz, quanto custa, quanto risco evita e quanto retorno já deu, com dados verificados e cases reais para transformar o painel da frota em decisão de orçamento aprovada. Leia mais » Telemetria sem sinal de internet: o que continua funcionando fora da área de cobertura Telemetria / 1 de setembro de 2026 Entenda o que depende de sinal de celular na telemetria veicular e o que continua funcionando fora da área de cobertura. Conheça a diferença entre captação por GPS e transmissão por rede celular, o que acontece com os dados sem sinal, e descubra como avaliar um fornecedor nesse cenário. Leia mais » Como avaliar fornecedores de gestão de frotas antes de fechar contrato Gestão de frota baseada em dados / 27 de agosto de 2026 Antes de fechar contrato com um fornecedor de sistema de gestão de frotas, vale comparar mais do que preço e lista de funcionalidades. Neste conteúdo, você vai entender a diferença entre telemetria básica, telemetria avançada, videoteleme', 'https://www.cobli.co/blog/'),
('d3fae752-589b-4b33-99b6-60ab68ea31de', 'noticia', 'Cobli, que monitora veículos com câmeras e IA, recebe aporte', 'A Cobli, fundada em 2017 por Parker Treacy e Rodrigo Mourad, é uma plataforma de inteligência para gestão de frotas que combina IoT, inteligência artificial, big data e videotelemetria para reduzir custos e aumentar segurança. Já captou mais de R$ 350 milhões, liderados por SoftBank, IFC e Fifth Wall.', 'https://exame.com/negocios/cobli-recebe-aporte-de-r100-milhoes-para-monitorar-eficiencia-logistica-com-cameras-e-ia/');

-- Loft
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('6cb48eb0-60aa-45e7-9b4f-77a2d7c024f9', 'Loft', null, 'Compra, reforma e venda de imóveis de alto padrão, com soluções tecnológicas para imobiliárias', 'scale-up (unicórnio desde janeiro de 2020)', 'São Paulo, SP', 'Compra, reforma, precifica e vende imóveis de alto padrão nas capitais, dependendo massivamente de avaliações técnicas e liquidez patrimonial real. Fundada em 2018 por Florian Hagenbuch e Mate Pencz (ex-fundadores da Printi), tornou-se unicórnio em janeiro de 2020.', 2018, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('6cb48eb0-60aa-45e7-9b4f-77a2d7c024f9', 'noticia', 'Loft Brasil Tecnologia (verbete)', 'Loft Brasil Tecnologia é uma empresa brasileira fundada em agosto de 2018 pelo alemão Florian Hagenbuch e pelo húngaro Mate Pencz (que antes cofundaram a Printi), sediada em São Paulo. Opera uma plataforma digital para compra e venda de imóveis, com serviços de financiamento, aluguel, garantias locatícias, reformas e seguros. Tornou-se unicórnio em 2 de janeiro de 2020.', 'https://pt.wikipedia.org/wiki/Loft_Brasil_Tecnologia'),
('6cb48eb0-60aa-45e7-9b4f-77a2d7c024f9', 'vaga', 'LOFT | Carreiras', 'Página de carreiras oficial da Loft (via Teamtailor), listando vagas abertas na empresa em tecnologia, operações e áreas de negócio.', 'https://loft.teamtailor.com'),
('6cb48eb0-60aa-45e7-9b4f-77a2d7c024f9', 'noticia', 'Loft, startup de imóveis, se torna o novo ''unicórnio'' brasileiro', 'A Loft, fundada em agosto de 2018 em São Paulo por Florian Hagenbuch e Mate Pencz, atingiu o valor de mercado de US$ 1 bilhão após um aporte de US$ 175 milhões liderado pela Vulcan Capital (fundo de Paul Allen, cofundador da Microsoft), com apenas 16 meses de operação — tornando-se o unicórnio mais rápido da história do país, com US$ 273 milhões captados no total até então. A empresa compra, reforma e revende imóveis usados, e planejava expandir para o Rio de Janeiro, Cidade do México e outras capitais.', 'https://www.suno.com.br/noticias/startup-loft-novo-unicornio-brasileiro/');

-- Sólides
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('6e74fc8d-a2a0-4da7-b41b-7173de6f9ddb', 'Sólides', 'https://www.solides.com.br', 'Software de RH e DP (mapeamento comportamental / Profiler) para pequenas e médias empresas', 'scale-up', 'Belo Horizonte, MG', 'Focada em softwares de RH, destaca-se pelo mapeamento comportamental (Profiler) estruturado em metodologias tradicionais de psicologia, além de ferramentas de departamento pessoal (folha, ponto, admissão) para pequenas e médias empresas.', 2010, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('6e74fc8d-a2a0-4da7-b41b-7173de6f9ddb', 'site_institucional', 'Sistema de RH e DP Completo: Economize até 40% | Sólides', 'Sistema de RH e DP Completo: Economize até 40% | Sólides Ir para o conteúdo 💡Mapa RH&DP 2026: Acesse a dados atualizados com comparativos e análises para transformar a sua gestão! BAIXAR GRÁTIS Teste Grátis Agendar Demonstração Portal de Vagas Portal de Vagas | Bater Ponto Entrar Bater Ponto Agendar Demonstração Sistema de RH e Departamento Pessoal Para todas as empresas que sobem no ringue pra vencer Sólides é a única tecnologia para Gestão de Pessoas que une estratégia e inteligência artificial em um só lugar , impulsionando negócios com soluções integradas de RH, Departamento Pessoal, Folha de Pagamento e Benefícios Corporativos. +55mil clientes +27milhões de vidas Agendar demonstração Testar gratuitamente Clique para assistir ao vídeo completo +27 milhões de vidas ◆ SÓLIDES #COMPLETADEVERDADE ◆ +55 mil clientes ◆ LUTE COMO UM CAMPEÃO ◆ +27 milhões de vidas ◆ SÓLIDES #COMPLETADEVERDADE ◆ +55 mil clientes ◆ LUTE COMO UM CAMPEÃO ◆ Somos a parceira estratégica das empresas brasileiras que não fogem da luta Mais de 55 mil clientes , de Norte a Sul, confiam na maior e melhor HR Tech do Brasil. Tecnologia peso-pesado para uma Gestão de Pessoas #CompletaDeVerdade Do Recrutamento à Retenção, são mais de 150 soluções integradas para que seu RH e Departamento Pessoal lutem como campeões. RH & Atração de Talentos Portal de Vagas e Banco Unificado de Talentos IA preditiva com match entre vaga e candidato Mapeamento com perfil ideal para contratações Saiba mais DP & Folha de Pagamento Controle de Ponto Digital com reconhecimento facial Folha de Pagamento 25x mais veloz e integrada ao eSocial SuperApp exclusivo para autogestão do time Saiba mais Inteligência Artificial Triagem automatizada com match e análise de perfil comportamental Ações de clima e prevenção de rotatividade com ', 'https://www.solides.com.br'),
('6e74fc8d-a2a0-4da7-b41b-7173de6f9ddb', 'blog', 'Blog Sólides | Os melhores conteúdos sobre gestão de pessoas', 'Blog Sólides | Os melhores conteúdos sobre gestão de pessoas Ir para o conteúdo ⚠️ RAIO-X DO CONARH ⚠️ Tenha acesso aos melhores conteúdos do maior evento da América Latina: ACESSAR MATERIAL GRÁTIS Pesquisar Pesquisar Conheça a Sólides Área do Cliente PEÇA UMA DEMONSTRAÇÃO News l etter Categorias Gestão de Pessoas e Liderança Recrutamento e Seleção Recursos Humanos Legislação Trabalhista Tecnologia e Inovação Departamento Pessoal Cultura Organizacional Benefícios Corporativos Desenvolvimento de Carreira Saúde e Bem estar no Trabalho Histórias de Sucesso Gestão Empresarial Inteligência Comportamental Materiais Gratuitos Central de Planilhas Gratuitas Encontre todas as planilhas de RH e DP em um só lugar e otimize seu setor. Calculadoras Gratuitas Faça cálculos dos principais custos e oportunidades de seu RH e DP. E-books e infográficos Materiais educativos com informações de valor para todos profissionais. Kits Gratuitos Acesso rápido a diversos materiais compilados em kits e um único download. Panorama Gestão de Pessoas A Sólides e a Offerwise mapearam o cenário da Gestão de Pessoas no Brasil. Escola de Pessoas Estude na maior plataforma gratuita de RH do Brasil Cases de Sucesso Cases da Sólides Conheça como a Sólides mudou o processo de gestão de pessoas dos clientes para melhor, otimizando o tempo de gestão e contratação. Eventos Eventos da Sólides Os principais eventos sobre Gestão de Pessoas, RH e DP da América Latina, você encontra aqui! Produtos Sólides Produtos para Departamento Pessoal Ponto Eletrônico Digital Folha de Pagamento Digital Controle de Férias Produtos para Recursos Humanos Recrutamento e Seleção Avaliação de Desempenho Pesquisa de Clima Organizacional Demais Produtos Sólides Teste de Perfil Comportamental Vale Alimentação e Refeição Empréstimo Consi', 'https://solides.com.br/blog/'),
('6e74fc8d-a2a0-4da7-b41b-7173de6f9ddb', 'noticia', 'Sólides (verbete)', 'Sólides Tecnologia S.A. é uma empresa brasileira de tecnologia com sede em Belo Horizonte (MG), fundada em 2010 por Mônica Hauck e Alessandro Garcia. Atua como uma HR Tech, desenvolvendo soluções digitais para Recursos Humanos e Departamento Pessoal, com foco em pequenas e médias empresas.', 'https://pt.wikipedia.org/wiki/Sólides');

-- Petlove
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('082f4daf-9878-4d03-914b-9890ef38e04b', 'Petlove', 'https://petlove.com.br', 'E-commerce e plano de saúde pet, com rede credenciada de clínicas veterinárias', 'scale-up', 'São Paulo, SP', 'Maior ecossistema de conveniência pet do país. Consolida a entrega de rações e medicamentos físicos, associada a uma vasta rede credenciada de clínicas veterinárias e a um plano de saúde para pets.', 1999, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('082f4daf-9878-4d03-914b-9890ef38e04b', 'site_institucional', 'Petlove: o maior petshop online do Brasil', 'Petlove: o maior petshop online do Brasil Informar CEP Compras recorrentes Meus pedidos Favoritos Meus dados Endereços Meus pets Avaliar produtos Meus créditos Meus pontos Stix Atendimento Indique e Ganhe Cachorro Rações Ração Seca Ração Natural Ração Úmida Ração Medicamentosa Alimentação Natural Alimentação Natural Fresca Alimentação Natural Congelada Petiscos e Ossos Cuidado Oral Petisco Natural Bifinhos Biscoitos e Snacks Ossos e Mordedores Molhos Petisco Cremoso Bolos e Chocolates Grama Digestiva Acessórios para Alimentação Comedouros Bebedouros Alimentadores Automáticos Porta Rações Jogo Americano e Acessórios Mamadeiras Medicamentos Antipulgas e Carrapatos Vermífugos Vitaminas e Suplementos Probióticos Anti-inflamatórios Antibióticos Antieméticos Sarnicidas Homeopáticos e Florais Tratamentos para Pele Tratamentos para As Orelhas Tratamentos para Os Olhos Tratamento Dentário Roupas Pós-cirúrgicas Colar Elizabetano Analgésico Antisséptico Shampoo para Tratamento Demais Medicamentos Acessórios para Saúde Tapetes Higienicos e Banheiros Tapetes Higiênicos Banheiros de Cachorro Fraldas Granulado Higiene e Limpeza Higiene Dental Eliminador de Odores e Desinfetante Lenços Umedecidos Coletor de Fezes Escovas, Tesouras e Rasqueadeiras Cortadores de Unha Limpa Patas Máquina de Tosa e Acessórios Shampoos e Cosméticos Shampoos Condicionadores Hidratantes Perfumes e Colônias Banho A Seco Desembaraçante Sabonetes Protetor Solar Brinquedos Mordedores Bolinhas Cordas Pelúcia Brinquedos Interativos Brinquedos de Nylon Frisbees Caminhas e Casas Caminhas Almofadas e Colchonetes Casinhas Mantas e Cobertores Roupas e Acessórios Moletons e Blusas Vestidos Roupas de Verão Capas de Chuva Colete Salva Vidas Fantasias e Aniversário Bandanas e Acessórios Coleiras, Guias e Peitorais Peitorais', 'https://www.petlove.com.br'),
('082f4daf-9878-4d03-914b-9890ef38e04b', 'blog', 'Dicas Petlove: Tudo sobre saúde, cuidados e bem-estar do seu pet', 'Dicas Petlove: Tudo sobre saúde, cuidados e bem-estar do seu pet OK! Busca Saúde Por que não usar o anticoncepcional para cachorro? Entenda os perigos Existe anticoncepcional para cachorro, mas o medicamento traz riscos sérios à saúde da cadela. Entenda por que a castração é a opção mais segura. Por Amanda Fernandes - 4 de setembro de 2026 Saúde Pimobendan para cães: o que é, como age e quando o médico-veterinário indica Por Amanda Fernandes - 3 de setembro de 2026 Nutrição Conheça a Royal Canin Exigent, a ração para gatos seletivos Por Amanda Fernandes - 2 de setembro de 2026 Bem-estar Gato sente calor? Saiba como refrescar o pet Por Amanda Fernandes - 31 de agosto de 2026 Doenças Conheça os tipos de dermatite canina, causas e tratamentos Por Amanda Fernandes - 28 de agosto de 2026 Saúde Para que serve a ivermectina para cachorro? Conheça opções Por Amanda Fernandes - 28 de agosto de 2026 Saúde Gato bebendo muita água? Entenda possíveis causas Por Amanda Fernandes - 27 de agosto de 2026 Novidades O melhor plano de saúde pet Plano de Saúde Petlove Contrate um dos planos de saúde Petlove. Garanta a melhor mensalidade, cobertura e atendimento. Solicite seu orçamento Farmácia de Manipulação Petlove Cada pet é único, o tratamento também pode ser 1 /2 Acesse outros conteúdos Doenças - 26 de agosto de 2026 Principais problemas de saúde do Buldogue Francês Entenda as particularidades da raça, aprenda a identificar os primeiros sinais de alerta e descubra como garantir a qualidade de vida do seu pet. Raças - 25 de agosto de 2026 Como é a personalidade do Lulu da Pomerânia? Também conhecida como Spitz Alemão Anão, a raça é ótima para famílias e chama atenção por seu temperamento marcante. Saúde - 25 de agosto de 2026 Causas da hérnia de disco em cachorro, sintomas e tratamentos ', 'https://www.petlove.com.br/dicas'),
('082f4daf-9878-4d03-914b-9890ef38e04b', 'noticia', 'Petlove: como o 1º e-commerce de pet virou uma empresa de bilhões', 'A história da Petlove começou em 1988, quando o veterinário Marcio Waldman abriu uma clínica e loja de produtos pet em São Paulo. Em 1999 a empresa lançou sua primeira loja virtual, batizada PetSuperMarket — o primeiro e-commerce de produtos pet do Brasil. Em 2012 a marca passou por um reposicionamento e adotou o nome Petlove.', 'https://exame.com/carreira/petlove-como-o-1o-e-commerce-de-pet-virou-uma-empresa-de-bilhoes/');

-- Nagro
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('d7c00195-c553-4aca-b368-fc205809e776', 'Nagro', 'https://www.nagro.com.br', 'Agfintech: crédito rural automatizado e análise de risco para pequenos e médios produtores', 'Series B (R$ 50 milhões liderados pelo Rabobank, total de R$ 97 milhões captados)', 'Uberlândia, MG', 'Agfintech que utiliza modelos preditivos e IA para realizar análises de risco de crédito rural automatizadas e liberar capital em tempo recorde para pequenos e médios produtores (faturamento entre R$500 mil e R$20 milhões/ano). Fundada em 2020 por Gustavo Alves, Leonardo Rodovalho e Vinícius Dutra.', 2020, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('d7c00195-c553-4aca-b368-fc205809e776', 'site_institucional', 'Nagro — Fintech de Crédito para o Agronegócio Brasileiro', 'Nagro — Fintech de Crédito para o Agronegócio Brasileiro Ir para o conteúdo principal BACEN · SCD · CMN 4.656/2018 Descomplicamos o dinheiro para você focar no que importa: produzir. Fintech regulada pelo Banco Central, especializada no agronegócio brasileiro. Soluções 100% digitais voltadas para o produtor rural. Solicitar Crédito Baixe o app BACEN Regulada Sem garantia real Aprovação em 24h 27 estados Investidores e parceiros institucionais Como funciona na prática Crédito regulado, com a velocidade do campo. ››› Da origem do capital ao PIX na sua conta — em quatro etapas auditadas pelo Banco Central. BACEN · Régua bancária Mesma régua dos grandes bancos. Sem o ritual deles. Sociedade de Crédito Direto autorizada pela Resolução CMN 4.656/2018. Operamos com capital próprio e de investidores institucionais — sem depósitos do público, sem áreas cinzas regulatórias. Auditoria independente anual. BACEN · CMN 4.656/2018 Fiscalização equivalente à dos bancos múltiplos O que isso entrega para o produtor: TLS 1.3, KYC e AML como padrão — não diferencial. Os mesmos protocolos exigidos de bancos múltiplos, aplicados em uma operação 100% digital. O caminho do capital Os 4 passos do crédito nagro . 01 Origem De onde vem o capital Recursos próprios + Fiagros (Fundos de Investimento do Agronegócio). Funding regulado, lastro auditado. 02 Estrutura Como o crédito é estruturado Analistas com vivência de campo avaliam perfil produtivo, ciclo de safra e capacidade de pagamento. Decisão em até 24h úteis. 03 Regulação O que o BACEN fiscaliza Cada contrato é registrado e reportado ao Banco Central. Compliance bancário integral. 04 Destino Como o dinheiro chega PIX direto na conta. Capital livre, sem garantia real até R$ 150 mil. Você define onde aplicar. Como o mercado avalia você Quatro pi', 'https://www.nagro.com.br'),
('d7c00195-c553-4aca-b368-fc205809e776', 'noticia', 'Nagro, a fintech do pequeno produtor rural, atrai o Rabobank e o Itaú', 'A Nagro, fintech fundada em 2020 que dá crédito a pequenos e médios produtores rurais, completou uma rodada Série B de R$ 50 milhões liderada pelo Rabobank (maior banco do agronegócio do mundo) e com participação do Itaú, somando R$ 97 milhões captados em equity até então. A empresa emitiu R$ 115 milhões em crédito no último ano e atingiu EBITDA positivo pela primeira vez; sua plataforma de análise de risco, a AgRisk, já atende 1.400 empresas.', 'https://braziljournal.com/nagro-a-fintech-do-pequeno-produtor-rural-atrai-o-rabobank-e-o-itau/'),
('d7c00195-c553-4aca-b368-fc205809e776', 'noticia', 'Nagro finaliza nova captação e recebe R$ 245 milhões de investimentos em 2023', 'Em rodada Série A liderada pela Kinea Ventures e pela Revolution, a Nagro somou R$ 245 milhões captados em 2023 ao combinar equity e linhas de crédito. A empresa já desembolsou mais de R$ 300 milhões a mais de 5.000 produtores rurais em 40 culturas diferentes e 2.000 municípios, usando os recursos para expandir sua plataforma de risco AgRisk e dois Fiagros de crédito.', 'https://startupi.com.br/nagro-nova-captacao/');

-- Datarisk
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('ba74df5a-26f7-43e0-9be5-00fe0aa80944', 'Datarisk', 'https://www.datarisk.io', 'Data Science as a Service: modelos preditivos sob demanda para crédito, evasão de clientes e fraude', 'scale-up', 'Florianópolis, SC', 'Opera como Data Science as a Service, construindo modelos preditivos personalizados sob demanda para análise de crédito, prevenção à evasão de clientes (ChurnAI) e detecção de fraude, com uma plataforma de MLOps para treinar, implementar e monitorar modelos de machine learning.', 2017, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('ba74df5a-26f7-43e0-9be5-00fe0aa80944', 'site_institucional', 'Datarisk – Como dados podem gerar valor a sua empresa', 'Datarisk – Como dados podem gerar valor a sua empresa Fale com nosso Time Destrave o potencial da Machine Learning Treine, implemente e monitore seus modelos com nossa plataforma de MLOps Saiba mais Melhoramos suas decisões através de dados Dominamos ferramentas de Machine Learning que maximizam o potencial de lucros e minimizam perdas de empresas nos mais variados segmentos. Conheça nossas soluções Antecipe cancelamentos antes que impactem sua receita recorrente. O ChurnAI identifica clientes em risco, explica os motivos e recomenda ações de retenção com precisão. Solicitar Demo Destrave o potencial da Machine Learning Treine, implemente e monitore seus modelos com nossa plataforma de MLOps Saiba mais Melhoramos suas decisões através de dados Dominamos ferramentas de Machine Learning que maximizam o potencial de lucros e minimizam perdas de empresas nos mais variados segmentos. Conheça nossas soluções Antecipe cancelamentos antes que impactem sua receita recorrente. O ChurnAI identifica clientes em risco, explica os motivos e recomenda ações de retenção com precisão. Solicitar Demo A Datarisk gera insights mudando a realidade Model as a Service Simplifique sua estratégia de Machine Learning com Model as a Service (MaaS) Com o Model as a Service (MaaS), sua empresa pode acessar modelos customizados de Machine Learning hospedados em nossa nuvem. Isso significa que você pode adicionar recursos de ML às suas aplicações sem precisar investir em hardware caro ou contratar especialistas em aprendizado de máquina Conheça nosso Model as a Service Histórias de Sucesso Como dados podem gerar mais valor para a sua empresa Como reduzimos o esforço de moderação e o tempo de atendimento às reclamações do Reclame AQUI Saiba como ajudamos o Reclame AQUI Datarisk aumenta em 65% a assert', 'https://www.datarisk.io'),
('ba74df5a-26f7-43e0-9be5-00fe0aa80944', 'blog', 'Blog – Datarisk', 'Blog – Datarisk Fale com nosso Time Artigos recentes Fique por dentro das notícias, pesquisas, artigos e conteúdos sobre o mercado e nossas soluções. Inteligência Artificial Datarisk agora é WeCogno: uma nova fase para transformar dados em decisões mais inteligentes Depois de anos construindo soluções de dados e inteligência artificial ao lado de empresas de diferentes setores, iniciamos um novo capítulo da nossa trajetória. A Ler mais » 17/08/2026 Como uma multinacional do setor de bens de consumo evitou rupturas e excessos de estoque na Páscoa com inteligência preditiva A cadeia de suprimentos da indústria de bens de consumo vive um paradoxo constante: errar para mais significa capital imobilizado e perdas; errar para menos Ler mais » 29/01/2026 Como usamos IA para a antecipar a utilização de planos de saúde e tornar decisões mais inteligentes A crescente complexidade do setor de saúde suplementar exige decisões cada vez mais rápidas e baseadas em dados. Um dos principais desafios das operadoras está Ler mais » 16/12/2025 Inteligência Artificial Tarifas, IA e Risco: Como a Nova Guerra Comercial Redesenha a Estratégia de Crédito O novo tarifaço dos Estados Unidos contra a China e outros países não é apenas uma manobra comercial. Ele representa um divisor de águas para Ler mais » 29/04/2025 Cases de Sucesso Como um banco digital reduziu em 21,5% a inadimplência com a Datarisk O Reclame AQUI é a maior plataforma de soluções de conflitos entre consumidores e empresas da América Latina, com mais de 20 anos de história… Ler mais » 02/04/2025 MLOps Datarisk anuncia seu produto de MLOps O maior problema que companhias enfrentam para a adoção de inteligência artificial em suas operações Durante os nossos 7 anos de história, a Datarisk buscou Ler mais » 27/08/2024 Trilha Jogos ', 'https://www.datarisk.io/blog/'),
('ba74df5a-26f7-43e0-9be5-00fe0aa80944', 'noticia', 'DataRisk recebe aporte de R$ 2,5 milhões do Fundo Criatec 2', 'A Datarisk, fundada em 2017 com investimento anjo, recebeu R$ 2,5 milhões do Fundo Criatec 2 (gerido pela Bozano Investimentos). A empresa desenvolve soluções automatizadas de modelos preditivos com IA, com plataforma de analytics voltada a fraude e crédito; lançou seu primeiro produto comercial em 2018 e já havia sido acelerada pela Visa e reconhecida entre as 100 startups mais inovadoras da América Latina. O aporte financiou desenvolvimento tecnológico e expansão comercial para novos setores.', 'https://canalexecutivoblog.wordpress.com/2019/05/21/datarisk-recebe-aporte-de-r-25-milhoes-do-fundo-criatec-2/');

-- UpFlux
insert into startups (id, nome, site, setor, estagio, localizacao, descricao_curta, ano_fundacao, tamanho_time) values
('d97253f2-8761-43d6-af84-4694ed93ce93', 'UpFlux', 'https://www.upflux.com.br', 'Process mining + IA para otimização de processos de compras e faturamento hospitalar', 'scale-up (aportes da Aggir Ventures e Alexia Ventures)', 'Jaraguá do Sul, SC', 'Mistura mineração de processos (Process Mining) e IA para analisar jornadas de pacientes e fluxos de faturamento em grandes redes hospitalares, cortando desperdícios. Primeira plataforma de process mining da América Latina, com mais de R$ 200 bilhões em transações processadas e clientes como Dasa, Unimed e MedSenior.', 2017, null);

insert into documentos (startup_id, tipo, titulo, conteudo_texto, url_fonte) values
('d97253f2-8761-43d6-af84-4694ed93ce93', 'site_institucional', 'UpFlux | Time digital de compras e saúde com IA no ERP', 'UpFlux | Time digital de compras e saúde com IA no ERP Diagnóstico Agendar demo Time Digital · resultado medido em reais Toda operação esconde ineficiência. Nós convertemos em dinheiro. Pedidos pagos acima do melhor preço da própria empresa, contas com cobrança indevida, prazos que ninguém cobrou. Um time digital trabalha transação por transação dentro do seu ERP, e cada real recuperado é provado. Seu time decide o que importa. Compras Saúde Descobrir o dinheiro na mesa R$ 200 B+ transacionados + 100 clientes 20 + indústrias Única BR no Gartner Market Guide O que já foi provado R$ 780 M+ em resultado gerado e auditado R$ 200 B+ transacionados em processos monitorados Única empresa do Brasil no Gartner Market Guide de Process Mining. Quem já prova em reais Agentes autônomos negociando compras em produção e auditando contas médicas em escala, em indústria, saúde, varejo e serviços. É a única empresa do Brasil reconhecida no Gartner Market Guide de Process Mining. O método Medimos onde vaza. Estancamos. Provamos quanto voltou . 1 Onde vaza Lemos o seu ERP transação por transação e mostramos onde a operação perde dinheiro: pedido pago acima do melhor preço da própria empresa, conta com cobrança indevida, prazo que ninguém cobrou. 2 Quem estanca Um time digital, agentes de IA operados por especialistas, assume a rotina dentro do ERP e trabalha o volume que o seu time não tem braço para cobrir. Seu time decide só o que exige julgamento. 3 Quanto voltou Cada real recuperado entra num placar auditável. Resultado medido, não prometido. Por onde a gente entra Duas portas, a mesma lógica: capacidade, não licença . Você compara com o que já gasta hoje para dar conta do volume: custo por transação e resultado medido. Compras Cada comprador ganha um time digital atrás de si. Negociaç', 'https://www.upflux.com.br'),
('d97253f2-8761-43d6-af84-4694ed93ce93', 'blog', 'Blog UpFlux | Process Intelligence, compras e saúde', 'Blog UpFlux | Process Intelligence, compras e saúde Diagnóstico Agendar demo // BLOG Além do Fluxo Process intelligence, compras, saúde e back-office. O que acontece quando um time digital assume o trabalho transacional, contado com números. Back-Office Compras indiretas: por que 80% dos fornecedores passam sem negociação, e como mudar isso Compras indiretas são o que mantém a empresa funcionando sem entrar no produto: MRO, facilities, TI, serviços. Elas concentram a maioria dos fornecedores e quase nenhuma negociação. Entenda por quê e o que fazer. 8 de setembro de 2026 Ler Back-Office Curva C em compras: como identificar no Protheus e no Datasul, e o que fazer com ela A curva C é a parte do gasto que ninguém negocia: pedidos pequenos, recorrentes, espalhados em dezenas de fornecedores. Veja como identificar a sua no ERP e por que colocar mais gente não resolve. 8 de setembro de 2026 Ler Saúde Como escolher tecnologia para operadoras de saúde sem cair em promessas vazias? Escolher tecnologia para operadoras de saúde exige critério, não fascínio. Veja o checklist que separa parceiros reais de promessas vazias. 31 de julho de 2026 Ler Gestão de Processos Os 5 imperativos do CPO em 2026, segundo o Hackett Group Conheça os cinco imperativos do CPO em 2026 e veja como IA, riscos, custos e eficiência redesenham as prioridades de procurement. 30 de julho de 2026 Ler Saúde Você conhece sua operação ou o relatório que alguém te vende sobre ela? Terceirizamos tudo. Inclusive o conhecimento sobre a nossa própria operação. Há uma forma de terceirização que raramente aparece nos contratos, mas que é considerada a mais cara de todas: a do conhecimento sobre o próprio processo. 26 de junho de 2026 Ler Back-Office 76% das empresas já colhem resultados de IA em Procurement Os resultado', 'https://www.upflux.com.br/blog'),
('d97253f2-8761-43d6-af84-4694ed93ce93', 'noticia', 'UpFlux, de Jaraguá do Sul, projeta expansão de 300% e chegada ao mercado internacional', 'A UpFlux, startup de process mining fundada em 2017 em Jaraguá do Sul (SC), integra-se aos ERPs de hospitais, laboratórios e clínicas para mapear o fluxo completo de processos — de contas a pagar a gestão de estoque — e comparar com modelos de referência, indicando onde clientes podem melhorar. Recebeu aportes da Aggir Ventures e da Alexia Ventures em 2021 e projetou crescimento de 300% para 2022, com clientes como Dasa, Unimed e MedSenior.', 'https://upflux.com.br/conheca-a-upflux/');
